### ISSUE TITLE
Version compatibility among PHP, PostgreSQL and ADOdb

### ISSUE THREAD

**Issue by fujiokae** [ADOdb/ADOdb#1004]
### Description
I have been using ADOdb for almost 20 years! Now I had to upgrade PostgreSQL from the very old 9.1 to 14. Then, I have found some incompatibility issues. I googled but failed to find quick information on whether any newer versions than PostgreSQL 9 are supported by ADOdb. Could you tell me what versions to use?
The existing, working versions are:
PHP 5.4, PostgreSQL 9.1, ADOdb 5.

The new version I'm trying to upgrade:
PostgreSQL 14.9.

So, which versions of PHP and ADOdb should I use? Or if ADOdb does not support PostgreSQL 14.9, which version of PostgreSQL should I use?

### Environment
- ADOdb version: ADOdb 5
- Driver or Module: 
- Database type and version: PostgreSQL 9.1 / 14.9
- PHP version: PHP 5.4
- Platform: Linux

### Issues
When MetaColumnNames() is called against PostgreSQL 14.9, it returns "current transaction is aborted, commands ignored until end of transaction block".
Also, adodb-postgres7.inc.php line 219 reports "Query failed: ERROR:  column d.adsrc does not exist LINE 1: SELECT d.adnum as num, d.adsrc as def from pg_attrdef d, pg_...". 
It seems that PostgreSQL 12 removed "adsrc" column.

**Comment by mnewnham** [comment]
- ADOdb should support the most current version of Postgres and there are currently no major unresolved issues with that.
- Your upgrade should encompass not just bringing Postgres up to date, but also use of **at least** PHP version 8.0 and ADOdb 5.22.6 in tandem with that. 
  - We no longer support PHP versions less than 7.4 in the current release
- Your ADOdb driver should be [postgres9](https://adodb.org/dokuwiki/doku.php?id=v5:database:postgresql)  This is the driver we are currently using as the basis for any changes required. 
  -  The call to _**adsrc**_ was superseded in the _**postgres8**_  driver

 Once you have all these elements in place, feel free to post additional questions. Good luck with your upgrade

**Comment by dregad** [comment]
@fujiokae you did not specify the exact ADOdb version you're using...

> adodb-postgres7.inc.php line 219 reports "Query failed: ERROR: column d.adsrc does not exist LINE 1: SELECT d.adnum as num, d.adsrc as def from pg_attrdef d, pg_...".
> It seems that PostgreSQL 12 removed "adsrc" column.

This problem was fixed in ADOdb 5.20.15, in the *postgres8* driver (see #562).

The reported error seems to imply that you're using the *postgres7* driver. I would recommend to use the generic `postgres` or `pgsql` aliases when initializing your DB connection, this way ADOdb will automatically use the latest available driver version (*postgres9* at the moment).

I have to admit that am no longer actively using PostgreSQL anymore, but in my tests using the *postgres9* driver, I have not experienced any compatibility issues up to PostgreSQL version 15.

That being said, I second what @mnewnham suggested, i.e. you should upgrade to the latest stable release (5.22.6 at the moment), which requires PHP 7.0 or later (not 7.4, that's for the upcoming 5.23.0). 

Upgrading PHP to 7.x or 8.x is no small undertaking, so if you are not ready to move past 5.x, then you should at least consider using the legacy ADOdb 5.21.4 release, which requires PHP 5.5.9 or later. Earlier ADOdb versions are no longer supported.

I hope this helps; I'll close this for now, feel free to reopen or create a new issue if you need more information.
