### ISSUE TITLE
Backtrace output is not channeled through ADODB_OUTP

### ISSUE THREAD

**Issue by cwmoss** [ADOdb/ADOdb#1018]
### Description
I want to log all sql statements to a file. I could do that using debug mode (1) and using an output-filter that removes html tags and logs to a file instead of sending everything to the browser.

```
define("ADODB_OUTP", "log_db_error");
function log_db_error($msg, $newline = "\n") {
   $msg = trim(strip_tags($msg));
   $msg = html_entity_decode($msg);
   $msg = "\033[1;34m" . $msg . "\033[0m";
   MyAppLogger::log($msg);
}
```

I don't want any output in the browser. that worked quite well. last year there was a change in `_adodb_debug_execute`. in case of a failure `_adodb_backtrace` is executed, regardless of debug-level. unfortunately this backtrace function doesn't go through the ADODB_OUTP filter, but instead prints the stacktrace to the browser.

would it be possible to change that behaviour? 
a/ make up a new debug level, that doesn't produce the stack trace
b/ make `_adodb_backtrace` filterable
c/ maybe there is a better option already to log sql statements without using debug, that I am not aware of

the change in question is here:

before (working well for my use case):
```
# in adodb-lib.inc.php, end of function _adodb_debug_execute
if ($zthis->debug === 99) _adodb_backtrace(true,9999,2);
```

after (undesired output to client browser):
```
if ($queryId === false || $zthis->debug === 99) {
   _adodb_backtrace(true, 0, 0, $isHtml);
}
```

**Comment by dregad** [comment]
> would it be possible to change that behaviour?
> a/ make up a new debug level, that doesn't produce the stack trace

I don't think that would be worth the effort and added complexity.

Please bear in mind that you are using a *debug* mode, the main purpose of which being to help troubleshoot issues in case of errors, not just to keep a trace SQL statements execution. The functionality is [clearly documented](https://adodb.org/dokuwiki/doku.php?id=v5:userguide:debug#possible_values):

> True | Standard mode, prints executed SQL statements and error information **including a Backtrace if the query failed.**

Forcing the backtrace's output in case of error is actually helpful in a debugging/troubleshooting context, which is why it was implemented that way when this code was refactored last year (see #863). 

> b/ make _adodb_backtrace filterable

I suppose you mean calling *ADOConnection::outp()* instead of *print* in *_adodb_backtrace()* ?

https://github.com/ADOdb/ADOdb/blob/fad4852a416fbbd4838964fb236804065bf047bd/adodb-lib.inc.php#L1379-L1381

If so, that would be a simple and low-impact change that we can certainly implement. Please confirm that this would indeed address your needs.

> c/ maybe there is a better option already to log sql statements without using debug, that I am not aware of

FYI, @mnewnham is currently working on a new logging system, that I believe would precisely address this in a more effective way. Please see #1019 for details.

**Comment by cwmoss** [comment]
> If so, that would be a simple and low-impact change that we can certainly implement. Please confirm that this would indeed address your needs.

Yes, I can confirm: using _ADOConnection::outp()_ instead of _print_ would solve my problem!

PS: the new logging system looks promising.
