### ISSUE TITLE
release versions????

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#147]
On the github wiki:
Stable Release Patches 	5.22.0-alpha.0
Current Production Version 	5.21.1
Earliest Supported Community Version 	5.19

Latest release on github.com/ADOdb/ADOdb: 5.19

?

**Comment by dregad** [comment]
This wiki is actually a work-in progress. I enabled it so that @mnewnham could evaluate the given features vs other solutions to replace the ADOdb website currently hosted at sourceforge.

The current version is still 5.19, I'm (still) hoping to release 5.20 soon. The rest is just tentative.

Sorry about the confusion - I will disable the wiki now.

**Comment by peterdd** [comment]
Sorry for disturbing again. Do you have something like a plan in mind for "release 5.20 'soon'"? Any unresolved blockers who blocks a release for unknown time?

End of Sepember 2015? October 2015? End of 2015? Next year?

It is because when pull request #149 accepted I can use coming ADOdb 5.20 release in an other project and doesn't have to program a workaround for this current bug.

**Comment by dregad** [comment]
The only real blocker is my lack of time...
