### ISSUE TITLE
Cannot call constructor

### ISSUE THREAD

**Issue by Sohorev** [ADOdb/ADOdb#172]
Fatal error: Uncaught Error: Cannot call constructor in /adodb5/drivers/adodb-postgres7.inc.php:100
Stack trace:
#0 /adodb5/adodb.inc.php(4741): ADODB_postgres7->__construct()
#1 /adodb5/adodb.inc.php(4611): ADONewConnection('postgres8')

**Comment by dregad** [comment]
This is a regression issue, caused by the fact that the postgres7 driver's constructor calls `parent::construct()`, which is no longer defined in postgres64 (see #171, 8ecd6a2a4a2e84f8f067c5d204452b20e70aff41).

Since the `ADOConnection` base class does not define a default constructor (and neither does PHP), we get this error.

**Comment by Sohorev** [comment]
It's work - thank you
