### ISSUE TITLE
What about PSR?

### ISSUE THREAD

**Issue by Sohorev** [ADOdb/ADOdb#173]
It would be good to use PSR
http://www.php-fig.org/

**Comment by dregad** [comment]
Which PSR are you talking about specifically ? Autoloader (0, 4) ? coding style (1, 2) ?

In any case, I have already given this some thought, but this is not a small undertaking as it requires a huge refactoring of the whole codebase.

**Comment by Sohorev** [comment]
Coding style to start

**Comment by dregad** [comment]
Well that actually *implies* the autoloader too 

> Namespaces and classes MUST follow an "autoloading" PSR: [PSR-0, PSR-4]. [[1]](http://www.php-fig.org/psr/psr-1/#1-overview)

For the record, I tried to run PHP_codesniffer on adodb.inc.php, got several thousands of errors thrown back at me, so this is not something that will happen very soon. But it's on the Radar, probably for version 6.

**Comment by dregad** [comment]
I will also need to discuss this with @mnewnham as he was originally leaning towards PEAR standards last time we discussed the roadmap.

**Comment by Sohorev** [comment]
I'll be happy to PEAR standard. You decide

**Comment by mnewnham** [comment]
This was not a group I was previously aware of, but I agree that the concept looks tempting. I'm sure that given the popularity of our project it would encourage long-term adoption of ADOdb. 

The main caveat, however, is as @dregad said, the required refactoring of the code into loadable classes, no small endeavour. It's already become an issue because of a desire to move towards PHPunit testing.

We recognize that the codebase does seem dated, and we are trying to make incremental updates to this with limited resources. We need to produce a stable, PHP 7 compliant version. With this in mind, I would guess that we could not even start looking at this until late 2016, by which time, who knows what standards/technologies will beckon us.
