### ISSUE TITLE
ODBC MetaColumns method returns MetaType instead of ActualType

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#184]
When the metaColumns method is called, the ODBC driver, and other drivers that use it as a  provider (including ACCESS) return the ADOdb metaType in the type field, instead of the actualType, as all other drivers. 

**Proposal 1**
ODBC driver is modified to return actualType, and for backwards compatibility, add ``$metaColumnsReturnsMetaType`` flag
**Proposal 2**
All other drivers modified to return MetaType value, and for backwards compatibility, add ``$metaColumnsReturnsActualType`` flag
**Proposal 3**
MetaColumns() method is modified to return both actualtype and metatype with option to return either actualtype or metatype in type field,

**Comment by dregad** [comment]
Based on your description it sounds like the "normal" behavior is to return actualType so it probably makes sense to go for option 1, but I don't have a strong preference.

If there is a use case for letting the caller chose what type they want, then option 3 makes sense (but not sure how you were thinking to set the option, via a parameter, or a property ?).

Instead of using a boolean flag, maybe an generic `$metaColumnsReturnType` with related constants META / ACTUAL would be more clear.
