### ISSUE TITLE
_adodb_getcount fails in v5.20

### ISSUE THREAD

**Issue by superhigi** [ADOdb/ADOdb#236]
_adodb_getcount used to work with v5.18 for the following queries:
SELECT &#x60;event_28&#x60;.* FROM &#x60;event&#x60; &#x60;event_28&#x60; ORDER BY (datestart) DESC
SELECT &#x60;eventreservation_35&#x60;.* FROM &#x60;eventreservation&#x60; &#x60;eventreservation_35&#x60; ORDER BY (SELECT CONCAT((datestart)) FROM event WHERE event.id=eventreservation_35.id_event) DESC, &#x60;ts&#x60; DESC

RegExp was: `/^\s*SELECT\s.*\s+FROM\s/Uis`

The new RegExp `/^\s*?SELECT\s.*?\s+(.*?)\s+FROM\s/is` creates faulty SQL.

**Comment by ipso** [comment]
This may have been caused by a commit I sent in a while back, I will dig into it more later today.

**Comment by ipso** [comment]
Yeah, this REGEX was changed in Pull Request #88 that I submitted a year ago.

I'm not sure there is much we can do here, ADODB will never be able to handle much more than the most basic types of queries. Once you start adding unions/sub-selects/JOINs/etc... there will always be substantial number of failure cases. 

The REGEX was originally changed a year ago (the code for which was posted to the PHPLENS forums in 2012) to try and catch a few more cases of more complex queries as it was low hanging fruit at the time, however I neglected to include examples of those queries then, but I think it was related to JOINs.

A bit more checking, it appears the old REGEX fails for a simple query like this:
`select col1,col2,col3,col4,
from table1
LEFT JOIN ( select col5 from table3 where col3=col4 ) as tmp;
`

But the new REGEX does work on it. So reverting back to the old REGEX isn't something I would recommend, as it would break other likely more used cases.

Anyways, to be honest, I'm not even sure I understand what your query is attempting to do, it seems to be like the previous count(*) behavior may have been valid SQL but also may return ambiguous results.

What the above mentioned pull request did add though was support to manually handle even the most complex queries, and that is by adding the _ADODB_COUNT keyword to the query, ie:

`SELECT _ADODB_COUNT `event_28`.* _ADODB_COUNT  FROM `event` `event_28` ORDER BY (datestart) DESC
SELECT `eventreservation_35`.* FROM `eventreservation` `eventreservation_35` ORDER BY (SELECT CONCAT((datestart)) FROM event WHERE event.id=eventreservation_35.id_event) DESC, `ts` DESC`

Anything between those keywords will be replaced by 'count(*)', when not running a count query they will be stripped of course.

**Comment by superhigi** [comment]
Thanks for the quick reply! I think I was not clear, I posted two different queries that do not work anymore:

-- Query #1 (pretty basic) --
SELECT `event_28`.* FROM `event` `event_28` ORDER BY (datestart) DESC;

-- Query #2 --
SELECT `eventreservation_35`.* FROM `eventreservation` `eventreservation_35` ORDER BY (SELECT CONCAT((datestart)) FROM event WHERE event.id=eventreservation_35.id_event) DESC, `ts` DESC;

Thanks for the tip with _ADODB_COUNT, I'll check that out too.

**Comment by ipso** [comment]
That makes more sense now, and you are correct those simple queries do fail, but adding one more space, at least two explicit columns to return, or a new line before the FROM makes them work, so the new REGEX has problems when the query is *too* simple.

My first message isn't quite correct, the original REGEX actually does seem to work when their are left joins, it may have stemmed from the /U modifier being missed during testing, since if I remove that than the PHPLENS forum post makes more sense, and the old REGEX isn't as robust as the new one, but with /U modifier there (like it should have always been), the new REGEX is worse, at least in the below test cases.

I'm thinking we should definitely have some unit tests around this, some examples that I used are:

Cases that should work:
`select col1 from table1; `

`select col1 from table1 LEFT JOIN ( select col5 from table3 where col3=col4 ) as tmp; `

`select col1,col2,col3,col4 from table1 LEFT JOIN ( select col5 from table3 where col3=col4 ) as tmp;`

`SELECT col1, 
col2, 
col3,
col4 FROM table
LEFT JOIN ( select col5 from table2 );`

`select 
col1,
col2,
col3,
col4,
from table1
LEFT JOIN ( select col5 from table3 where col3=col4 ) as tmp;`

`select _ADODB_COUNT col1,col2,(select col99 from table),col4 _ADODB_COUNT from table1 LEFT JOIN ( select col5 from table3 where col3=col4 ) as tmp;`


Cases that fail:
`select col1,col2,(select col99 from table),col4, from table1 LEFT JOIN ( select col5 from table3 where col3=col4 ) as tmp;`

Now that I double checked the usage of /U modifier, I haven't come up with a query that the new REGEX works on where the old one doesn't yet, but the very simple query is at least one example where the new REGEX causes a regression... So I think a change is needed either way, and simply reverting back to the original REGEX may be the best bet at this stage, what do you think @dregad?
