### ISSUE TITLE
More meaningful error when pg_connect is not available

### ISSUE THREAD

**Issue by arthur-clifford** [ADOdb/ADOdb#263]
I was setting up a new server with PHP7 and postgres 9 on an Ubuntu Linux OS and was getting an error:
 Missing extension for postgres.

"Extension postgres" is not clear as it is unknown as to whether you mean an adodb extension, a php extension, an apache/web-server extension etc. 

After digging through code I realized in adodb-postgres64.inc.php (which the other postgres versions ultimately inherit) that you are using pg_connect.

I did an additional check in a simple test script and realized that pg_connect was not installed by default and had to do:
sudo apt-get install php7.0-pgsql
sudo service apache2 restart

My request, then, is that the error message reflect the problem better.
In my version of the adodb-postgres64.inc.php script on line 693 (first line in _connect function):
if (!function_exists('pg_connect')) return null;

Instead of returning null, or wherever that null value is received, it would be better to throw an error saying that the pg_connect function could not be found and provide a clue as to what to do about it.

I ended up here and was savy enough to adapt the suggests for php7.0:
http://stackoverflow.com/questions/7438059/fatal-error-call-to-undefined-function-pg-connect

It might be good to consider providing dependency info in your help doc for the different database tech your using. If you do, I didn't run across it when searching adodb php missing extension postgres

**Comment by mnewnham** [comment]
The error message 'extension not installed' is ,I agree, somewhat terse, but it is correct. The question for technical documentation is always how far off topic should it go in order to be helpful.  There has to be an assumption on our part that the person implementing the ADOdb installation has a competence in PHP, the database they want to run and the platform they want to run it on.

Here's a line from the first page of the [Implementation document for ADOdb](http://adodb.org/dokuwiki/doku.php?id=v5:userguide:learn_abstraction:start_lesson)

**ADOdb is not a replacement for the PHP database driver, which must be installed and correctly configured.**

So the message **_extension not installed_** just means that the task specified above has not been completed correctly.  By broadening out the scope of the error message beyond the minimal 'driver not installed',  you are asking for is for us to multiply out our levels of support to include issues related the configuration and implementation of PHP/database connections, which we simply don't have the resources to do. A google search of "PHP database connection problem" + each of the most popular databases brings up an average of 1.8 million hits for each question, so as you yourself have discovered, dealing with the problems related to the configuration of PHP and the database connection is best left to sites like Stackoverflow, or database manufacturers forums.

That being said, I will add a note to the documentation explaining the error (but not in detail). If you are interested, you are welcome to write implementation tutorials for ADOdb and I will add them to the documentation so that others can learn from your experiences.

**Comment by arthur-clifford** [comment]
I understand where you are coming from

 

The line you cited if it had been on this page would have saved me some grief. 

http://adodb.org/dokuwiki/doku.php?id=index

 

Maintaining the higher level of descriptiveness you are aiming for, it is useful to know/remember that ADODB is not replacing things. 

 

Any chance I could convince you to that the error message might be better saying “Missing PHP Extension for ” when you know it is a missing PHP extension?

 

I’m a sysadmin, php developer, front end developer, and db admin and getting ADODB working is not something I have had to do more than a hand full of times over the last decade and half because it general just works; which is why I like it. So when I finally do have to implement it somewhere new it would be nice to have a hint as to which part of total infrastructure I’m missing without having to dig through documentation. 

 

I may take you up on your offer to do an implementation tutorial a little later. 

 

Thanks for acknowledging the request at least. Thanks for all you do.

 

Art C

**Comment by dregad** [comment]
> The line you cited if it had been on this page would have saved me some grief. 
> http://adodb.org/dokuwiki/doku.php?id=index 

Added the following paragraph:
_Note that ADOdb is not a replacement for the native PHP database extensions, but is built on top of them. This means that the corresponding driver(s) must be installed and correctly configured for ADOdb to work._ 

> Any chance I could convince you to that the error message might be better saying “Missing PHP Extension for ” when you know it is a missing PHP extension?

I have no objection to that; feel free to submit a pull request against latest master branch with the proposed change in code, I will be happy to review and merge it.

> I may take you up on your offer to do an implementation tutorial a little later. 

That would be great indeed. Looking forward to your contribution.

**Comment by dregad** [comment]
@arthur-clifford as you have not provided any feedback, I assume you're happy with the above-mentioned changed. Let us know if you do get around to writing the tutorial.
