### ISSUE TITLE
Undefined constant error when old ADOdb 5.04 Extension is loaded

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#269]
I got a bug report on https://bugs.flyspray.org/2189 and trying to analyze that seems to be related to ADOdb:

```php
<?php print_r(get_defined_constants(true)); ?>
...
 [ADOdb] => Array
        (
            [ADODB_EXTENSION] => 5.04
...
```

in adodb.inc.php line 91:
```php
 if (!$ADODB_EXTENSION || ADODB_EXTENSION < 4.0) {
...
 line 116: 
define('ADODB_ASSOC_CASE_LOWER', 0);
define('ADODB_ASSOC_CASE_UPPER', 1);
define('ADODB_ASSOC_CASE_NATIVE', 2);
```

That constants seems to be introduced with this commit 4 Mar 2013 5.18/5.19: 
https://github.com/ADOdb/ADOdb/commit/e3c11ed98970408eae649f929898983c6b5d2a6a

I'm now a bit unsure how to solve this in a general and best future proof way..
I have hackish workarounds in my mind, but maybe you know a solid solution?

If you want test, all-inkl.com provides a free 1-week test account. They provide also mantisbt as "one click install", but their install seems to use ADOdb5.10, so I didn't get that undefined constant ADODB_ASSOC_CASE_NATIVE Warning there.

**Comment by dregad** [comment]
The ADOdb Extension is no longer supported, and hasn't been updated for many years (to my knowledge, 5.04 was the last released version).

As a permanent fix, we should remove all references to its use from the code, so that the library relies exclusively on its own PHP objects.

Until then, as a workaround I suggest to work with the hosting provider so they discontinue use of obsolete software (i.e. disable ADOdb Extension from their PHP config). 

You may also want to try manually disabling the extension by modifying adodb.inc.php:
```
diff --git a/adodb.inc.php b/adodb.inc.php
index 821ab2c..0d8d079 100644
--- a/adodb.inc.php
+++ b/adodb.inc.php
@@ -70,7 +70,7 @@ if (!defined('_ADODB_LAYER')) {
    // GLOBAL SETUP
    //==============================================================================================
 
-   $ADODB_EXTENSION = defined('ADODB_EXTENSION');
+   $ADODB_EXTENSION = false;
 
    // ********************************************************
    // Controls $ADODB_FORCE_TYPE mode. Default is ADODB_FORCE_VALUE (3).
```

**Comment by dregad** [comment]
Note: if you can confirm that solves the problem, I can do a 5.20.6 hotfix release pending the actual code cleanup which should take place in a feature release.

**Comment by peterdd** [comment]
If I set the variable $ADODB_EXTENSION = false; in adodb.inc.php
the other constants raise the warning because they get double defined, which is not allowed.


```
Notice: Constant ADODB_BAD_RS already defined in /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php on line 94
Notice: Constant ADODB_TABLE_REGEX already defined in /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php on line 97
Notice: Constant ADODB_FETCH_DEFAULT already defined in /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php on line 117
Notice: Constant ADODB_FETCH_NUM already defined in /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php on line 118
Notice: Constant ADODB_FETCH_ASSOC already defined in /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php on line 119
Notice: Constant ADODB_FETCH_BOTH already defined in /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php on line 120
Notice: Constant ADODB_PHPVER already defined in /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php on line 157
Warning: session_start(): Cannot send session cache limiter - headers already sent (output started at /www/htdocs/w014f122/test92133.test-account.com/vendor/adodb/adodb-php/adodb.inc.php:94) in /www/htdocs/w014f122/test92133.test-account.com/setup/index.php
```

I mailed all-inkl.com on monday, no anwser yet. Will call them today.

**Comment by dregad** [comment]
I've been thinking about this some more; in fact it's probably a good thing that an error occurs when the ADOdb extension is loaded, because there's no telling what kind of side-effects could take place when using C code from <= 5.04 with the current PHP library.

So in fact, we should trigger a "proper" error when the Extension is detected.

**Comment by peterdd** [comment]
Got anwser: They said, they can't simply update the extension because - as you said - 5.04 is last version build as extension and that that extension is in use for other things. So they suggested to use PHP7, because there the ADOdb 5.04 extension is not loaded.

That raises two questions in my head: 
1. What gain you get if it is loaded as extension and if yes, 
2. Why ADOdb dropped that possibility to be built as extension.


Yes, maybe side-effects, but I'm not expert in that area.
So probably my part for Flyspray is 
1. adding a check at Flyspray installer if old adodb extension is loaded and 
2. make it PHP7 ready (fix warnings)

**Comment by dregad** [comment]
> They said, they can't simply update the extension because [... it]  is in use for other things

This argument does not make any sense. The PHP methods will work just fine without the extension (although potentially slower). The only case where someone could actually face issues, would be if they called the extension's functions directly (e.g. `adobd_getall($rs);` instead of `$rs->getArray();`.

> 1. What gain you get if it is loaded as extension

The Extension replaces some key ADOdb methods with C code, for better performance. I don't have any benchmarks on what kind of improvement that would give.

However, today that comes at the cost of potential unwanted side-effects / incompatibilities due to running 5.20.x PHP code with 5.04 C code, as mentioned earlier.

> 2. Why ADOdb dropped that possibility to be built as extension.

You would have to ask that question to John Lim, but my guess is because extra effort was required to keep the extension in sync with the PHP code.

In any case, fact remains that today is that **the Extension is obsolete, unmaintained and unsupported**; I don't even have the original source code for it (although someone found a Debian-specific version of it, see #84). Consequently, **I strongly recommend not to use the Extension**.

For the record, based on the Debian [source code](https://anonscm.debian.org/cgit/pkg-php/php-adodb.git/tree/adodb.c), I noticed that the ADODB_TABLE_REGEX constant does not have the same definition. I don't know what other inconsistencies there are.

> So probably my part for Flyspray is 
> 1. adding a check at Flyspray installer if old adodb extension is loaded and 

As I said, I can propose a 5.20.x hotfix to die() with an error message or throw an exception if the ADOdb Extension is detected.

**Comment by peterdd** [comment]
> As I said, I can propose a 5.20.x hotfix to die() with an error message or throw an exception if the ADOdb Extension is detected.

Maybe an exception instead just dying. So it can be handled userfriendly by applications?

**Comment by dregad** [comment]
Yes, that was the plan... read the sentence you quoted again :wink:
