### ISSUE TITLE
Prepare, SelectLimit & oci8po driver is throwing error

### ISSUE THREAD

**Issue by eharris200** [ADOdb/ADOdb#282]
oci8po driver, windows 7, IIS 7.5 PHP 7.0.11, oracle 12.1.0.2 adodb 5.20.7

Code seems to be ok in mysqli and mssqlnative adodb driver

$sql = 'select * from users where username = ?';

$handle = $dbConn->Prepare( $sql );

$result = $dbConn->getAll( $handle, [ 'username' ] ); // Works

$result = $dbConn->SelectLimit( $handle, 1, -1, ['username'] ); // Does not Work.  
Error:
PHP Warning:  strpos() expects parameter 1 to be string, array given in C:\inetpub\wwwroot\adodb5\drivers\adodb-oci8.inc.php on line 718
PHP Notice:  Array to string conversion in C:\inetpub\wwwroot\adodb5\drivers\adodb-oci8.inc.php on line 736

**Comment by dregad** [comment]
SelectLimit() tries to apply a *FIRST_ROWS* hint to the given SQL query, but doesn't account for prepared statements (where $sql is an array).

I would propose to add a check to only apply the hint when given a SQL string, and ignore prepared statement. Thoughts ?

Note: I don't have an available Oracle setup to test this at the moment.

**Comment by eharris200** [comment]
I think that will work.  I can test the change as I have an oracle dev env I can test against.

**Comment by dregad** [comment]
Can you try this ?

``` patch
diff --git a/drivers/adodb-oci8.inc.php b/drivers/adodb-oci8.inc.php
index a3b1b7d..ebbe81b 100644
--- a/drivers/adodb-oci8.inc.php
+++ b/drivers/adodb-oci8.inc.php
@@ -704,7 +704,7 @@ END;
    function SelectLimit($sql,$nrows=-1,$offset=-1, $inputarr=false,$secs2cache=0)
    {
        // seems that oracle only supports 1 hint comment in 8i
-       if ($this->firstrows) {
+       if ($this->firstrows && is_string($sql)) {
            if ($nrows > 500 && $nrows < 1000) {
                $hint = "FIRST_ROWS($nrows)";
            }
```

**Comment by eharris200** [comment]
ok,
  looks like that drifted into another error:

PHP Notice:  Array to string conversion in C:\inetpub\wwwroot\adodb5\drivers\adodb-oci8.inc.php on line 736

looks like there will probably need to be an is_array() check and pull $sql[0] if it is.  Or, instead of discussed patch, first thing it could do is check $sql for array and if so, set $sql = $sql[0].   

function SelectLimit($sql,$nrows=-1,$offset=-1, $inputarr=false,$secs2cache=0)
	{
             if( is_array( $sql ) ){
                 $prepSql = $sql;
                 $sql = $sql[0]; //assume it's a prepared statement.  Could check $sql[1] as well vardump oci8 statement type
             }

Problem with this approach though is now you prepared a statement but selectlimit() has modified it, so it's no longer your prepared statement.  You could call Prepare() on the statement that was modified by SelectLimit() ( build new sql statement, prepare it, if good, move forward ) , but now it's crossing over and doing other functionality.   Also don't know framework well enough to know if ADOCONNECTION is handling for you at a lower level this scenario.

I'll try and make some time and see how mysql handles this scenario with prepared statements and selectlimit.

**Comment by dregad** [comment]
Thanks for the feedback.

> looks like that drifted into another error:
PHP Notice: Array to string conversion in C:\inetpub\wwwroot\adodb5\drivers\adodb-oci8.inc.php on line 736

Just realized that error actually was in your original report already... sorry.

> call Prepare() on the statement that was modified by SelectLimit() 

I'm not sure that's a good idea.

Maybe just go for the risk of degraded performance, and execute SelectLimit on the original, non-optimized SQL string in all cases, since SelectLimit is most likely going to be used in situations where the caller only wants to return a small number of rows, so the benefits of hinting or optimizing is negligible.

**Comment by eharris200** [comment]
Yeah, didn't really like the prepare() on selectlimit().  Just wanted to throw out there.

Thanks for work on this project.  When you have another patch let me know and I'll test it out.

**Comment by dregad** [comment]
@eharris200 I finally fixed my Oracle setup (don't ask), and made some tests on this.

While replacing the prepared statement received as parameter in selectLimit by its SQL string as per your suggestion works just fine with the base oci8 driver, the oci8po chokes on it when there are parameters.

The reason is that the original query `SELECT * FROM table WHERE col = ?` is converted to `SELECT * FROM table WHERE col = :0`. This string is then used in selectLimit() to build a new query:

```
SELECT /*+FIRST_ROWS*/ * FROM table WHERE col = :0
-----<hr>
(oci8po): select * from (SELECT /*+FIRST_ROWS*/ * FROM table WHERE col = :0) where rownum <= ? 
   [ (0=>'value') (1=>'1')  ]
-----<hr>
PHP Notice:  Undefined offset: 2 in /home/dregad/dev/adodb/drivers/adodb-oci8po.inc.php on line 80
```

I'm not sure how to handle this, need further investigation. But for now I'm tempted to prevent the use of selectLimit with prepared statements in oci8po driver.

Let me know your thoughts.

**Comment by eharris200** [comment]
I think preventing the use will be fine.

**Comment by mnewnham** [comment]
I know I'm late into the conversation, but if i remember back to a discussion with John, probably 7 or 8 years ago when I started using oci8po, the binding stuff has never worked correctly, and there was an (unwritten) assumption that if you wanted to use bindings, you should avoid it. I remember when I did a lot of fixes for that driver, I simply avoided the binding stuff.

I don't think the oci8po driver gets a lot of use (I've abandoned using it now because oci8 is much faster), so perhaps having it fail nicely is the appropriate solution.
