### ISSUE TITLE
setSessionVariable and setSessionInitSql have overlapping functions

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#328]
I'm wondering whether we should eliminate the setSessionVariable method as its usage substantially overlaps the setSessionInitSql method, and in addition, it is difficult to use  when the parameters do not match the normal key=>value pair configuration. take for example the MySQL call
````
SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
````
which would be difficult to configure with the setSessionVariable method

**Comment by ipso** [comment]
I will need to refresh my memory, but if I recall the original intention of the session variables was to eventually handle cross database values that each driver could actually handle in a consistent way. Since I didn't want to modify any existing ADODB code on the first iteration, I decided to leave it in as a proof of concept.

Technically there is nothing preventing the load balancing from working across multiple databases too, though that isn't a use case we need right now,  but it's one where consistent cross database session variables would be useful.

I will get more information for you tomorrow.

**Comment by ipso** [comment]
Yeah, checking the code I see I have comments mentioning that setSessionVariable() is a candidate for moving into ADODB drivers and in our own application use setSessionInitSQL() instead with queries specific to each database that we support. 

While I believe it would be nice to have a set of "standard" session variables that can be used across all databases, (ie: setting the timezone, datestyles, etc...) similar to how transaction isolation modes are already handled, the majority of that work will need to be done in the drivers themselves and outside the scope of an initial release at this point. 

So how would you like to proceed, remove the code, comment it out, or leave it in? I'm fine with either.

**Comment by mnewnham** [comment]
I think we should remove it, we should start with a nice clean code base, and if you need it again its easy enough to retrieve

**Comment by ipso** [comment]
Its been so long since I've looked at this code, I dug into it more and realized that setSessionVariable() has a very important purpose that is separate from setSessionInitSQL(). 

setSessionInitSQL() just executes SQL queries upon initializing a new connection to a database. So these queries are only run once ever. The use-case here is setting one-off things like default date styles, SQL mode in MySQL, wait timeouts, things like that...

setSessionVariable() is used to keep session state synchronized across multiple connections. When existing or new variables are set they are executed on all open connections AND upon new database connections. Use case here are things like switching time zones in the middle of an existing connection.

So both of these should exist as they serve different yet similar purposes.
