### ISSUE TITLE
getLoadBalancedConnection returns incorrect value

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#331]
In the following scenario:
````
1 Write node
3 read-only nodes
2 of the 3 read-only nodes have failed
````
If the method getLoadBalancedConnection('readonly') is called before any database operation is performed, the node number returned is incorrect.

If  any database operation is performed prior to getLoadBalancedConnection, the correct value is returned

**Comment by ipso** [comment]
getLoadBalancedConnection() has to be as fast as possible and therefore just returns a connection based on the current in-memory data structures, it doesn't check for failed connections, thats handled in getConnection() instead.

Thats why you see the difference between calling it before or after a database operation has been performed, because once an operation has been performed if it fails then that connection is removed from the pool immediately upon failure/exception.
