### ISSUE TITLE
getconnectionbyweight randomizer doesn't check for invalid connections

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#332]
When used to check readonly connections, the method returns a random node number based on the number of nodes available, but doesn't check to see if the connection is valid.

**Comment by ipso** [comment]
That is correct, that function is designed to just get the connection of a specific type by weight, the getConnection() function is what actually checks to see if the connection is valid or not. If a connection isn't valid, getConnection() removes it from the pool so it won't be returned by getConnectionByWeight() any more.

**Comment by mnewnham** [comment]
I'm wondering then, that if all of these methods return unreliable results before the first connection is established, we should disallow their use (simply return false) before then

**Comment by ipso** [comment]
I wouldn't consider it unreliable, you need to use the functions for their intended use case is all.

What's the use case you had in mind for calling this function directly? 

What exactly is your definition of a "valid" connection and how do you propose checking that exactly?

**Comment by mnewnham** [comment]
@ipso , I seem to have hit a blockage on the difference between what I imagine the public methods are supposed to do, and what you say they actually do. I wonder if you might do me a favour and review the [documentaion](http://adodb.org/dokuwiki/doku.php?id=v5:loadbalancer:index) that I have produced so far, and provide a simple 'real world' example for getConnection, getLoadBalancedConnection, removeConnection and $enable_sticky_sessions.  If you could drop them here, I can use them as the basis for testing and updating the documentation.  Thanks

**Comment by ipso** [comment]
getConnection() would likely rarely be used, only if the developer needs to manage connections themselves manually rather than have the load balancer do it for them automatically. Perhaps in a case where the load balancer can't automatically determine if the query is write or read-only, especially if there are stored procedure calls involved, since its impossible to know what they do under the hood.

getLoadBalancedConnection() is called by getConnection(), it is public along with getConnectionByWeight() mainly to allow added flexibility if the developer wants to handle connections more themselves (perhaps custom weight calculating systems? Or perhaps to somehow take into account load on each server to load balance that way instead). These functions could be made private if you are concerned about them. If it were me I would probably just leave them public and not document them (at least in the first release) to be honest. I have no idea what use-cases people will come up with that may require them in the future, so I tend to error on the side of more flexibility rather than less.

removeConnection() might be used to remove connections in cases where they may be overloaded but haven't actually failed yet... For example they might just be returning too slowly. Also perhaps if something has failed but the load balancer hasn't or can't detect it. (ie: replication failed within the database server itself, but the connections from PHP are still valid and up) I'm sure there are a ton of other possible use cases for it too.

$enable_sticky_sessions is mostly a optimization setting that I believe should be enabled by default (which it is of course). The primary use-case for disabling this is if the developer knows they are going to be running a ton of heavy queries and they want to truly load balance at the per-query level rather than the per-request level. Since connecting to the database (especially some of the heavy databases like PGSQL) can take longer than running a few queries, it doesn't make sense to startup 5 connections to run 5 separate queries, when all 5 queries could be run on a single connection in less time. However if the developer needs to run 1000 queries in a row (ie: batch job), it might make sense to startup 5 connections and load balance all 1000 queries across those connections.

**Comment by mnewnham** [comment]
I've added your comments to the documentation
