### ISSUE TITLE
Request For Help - Feature difference between mssql and mssqlnative functions

### ISSUE THREAD

**Issue by mnewnham** [ADOdb/ADOdb#337]
### Issue
When handling bind parameters , there are substantial feature differences between the mssql and mssqlnative drivers

### History
The mssql driver was written by the original code author and community enhanced over a period of 10-15 years. The mssqlnative driver was not derived from the mssql driver, bu was written from scratch and provided my microsoft when the new php driver was released.

### Requirements
A member of the ADOdb community with expertise in Microsoft SQL Server review the _query() method in the drivers/adodb-mssql.inc and drivers/adodb-mssqlnative,inc includes and issue a recommendation as to whether the current feature in the mssql driver be imported into the mssqlnative driver

**Comment by obmsch** [comment]
Surely not an expert on the php side, but at least a user and some knowledge on mssql. I am quite sure
"_query" as it stands in "adodb_mssqlnative.inc" works fine on recent php and msphpsql drivers
(My MantisBT with php 5.3-7.1, msphpsql 3.?-4.1, never(~2012+) had an issue with it).

From the docs (https://docs.microsoft.com/en-us/sql/connect/php/sqlsrv-query);

sqlsrv_query( resource $conn, string $tsql [, array $params [, array $options]])

$params [OPTIONAL]: An array of values that correspond to parameters in a parameterized query.
Each element of the array can be one of the following:

  A literal value.
  A PHP variable.
  An array with the following structure:
    Code array($value [, $direction [, $phpType [, $sqlType]]])

_query(adodb_mssqlnative.inc) only uses $params if an $inputarr is given:
Line 583: $rez = sqlsrv_query($this->_connectionID, $sql, $inputarr);

As it stands $inputarr is an array($value) so $direction=SQLSRV_PARAM_IN is implied and as $phpType,
$sqlType are missing, default mapping of $value is used by the sqldriver for PHPTYPE to SQLTYPE
conversion (https://docs.microsoft.com/en-us/sql/connect/php/default-sql-server-data-types).

The code in _query(adodb_mssql.inc) does a manual mapping of the phptypes to the sqltypes, for a
completely differently sqldriver. The only difference I see is the handling of bools (-> sqltype INT) there.
But as the comment says, this is due to the support of older sqlserver versions lacking the BIT datatype. Which is not the case with mssqlnative.

IMHO no reason to change current code, we wouldn't do more than than the default mapping already
does.

Martin

**Comment by mnewnham** [comment]
Ok, thank you for that feedback. I will not make any changes to this code
