### ISSUE TITLE
getAssoc() does not like numbers as second column

### ISSUE THREAD

**Issue by Rubber-Telly-Media** [ADOdb/ADOdb#339]
I have a large old project that is failing due to getAssoc() not creating the correct array;

record set say:
"cheque_billing", 1
"cash_billing" , 1
"cc_billing", 0

Becomes Array;
'cheque_billing' => cheque_billing
...ect...

I get a copy of the first column as a String, instead of the second column's Numeric Value.

**Comment by Rubber-Telly-Media** [comment]
BTW: Driver in use is MySQLi

**Comment by dregad** [comment]
Which version of ADOdb do you use ?

**Comment by Rubber-Telly-Media** [comment]
5.20.9

**Comment by dregad** [comment]
There are several known issues with getAssoc() in 5.20.9 (see #189, #198, #204, #335), which will be fixed in 5.21.0. Please test your code using the latest code in _master_ branch, hopefully that will resolve your issue.

I'm going to close this for now, feel free to reopen the issue if the problem persists.
