### ISSUE TITLE
Some special characters in passwords break ADONewConnection

### ISSUE THREAD

**Issue by rannmann** [ADOdb/ADOdb#354]
## Description
After migrating a project from a PHP 5.3.3 server to PHP 5.6.30, I couldn't connect via mysqli.  This appears to be related to changes in `parse_url` between versions fixing a bug where colons could be passed inappropriately.

I'm honestly not sure why this used to work though.  It really never should have.

## Steps to reproduce
1. Create a MySQL user with a password having a special `#` character preceded by a `:`, but with at least one character in between the two.  (ex: `part:of#password`)
2. Create a new ADO connection with a mysqli connection string.  Ex: `ADONewConnection('mysqli://test_user:pass:word#@localhost:3306/test_databases');`

## Expected result
Connect to the database and return an object

## Actual result
Returns false.

## Other Comments
A convenient way of testing this: 
```php
// Fails
var_dump(parse_url( 'mysqli://test_user:pass:word#@localhost:3306/test_database' ));
```

**Comment by dregad** [comment]
I can confirm the behavior - Tested with PHP 5.6.30 the above command yields

```
array(6) {
  ["scheme"]=>
  string(6) "mysqli"
  ["host"]=>
  string(9) "localhost"
  ["port"]=>
  int(3306)
  ["user"]=>
  string(9) "test_user"
  ["pass"]=>
  string(10) "pass:word#"
  ["path"]=>
  string(14) "/test_database"
}
```

And with later versions (tested with 7.0.20 and 7.1.6), it returns `bool(false)`.

Since this can be reproduced without using ADOdb, I would suggest you report it as a PHP bug; it would be nice if you could post the link to it here, for reference.

That being said, [as per RFC 3986](https://tools.ietf.org/html/rfc3986#appendix-A), the _userinfo_ element is defined as follows
```
userinfo      = *( unreserved / pct-encoded / sub-delims / ":" )

unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded   = "%" HEXDIG HEXDIG
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="
```

which means that the use of `:` and `#` is not valid (the characters it should be percent-encoded).

**Comment by dregad** [comment]
I think you should just `rawurlencode()` the password when building the DSN URI. [ADONewConnection will decode it](https://github.com/ADOdb/ADOdb/blob/v5.20.9/adodb.inc.php#L4710)
