### ISSUE TITLE
RecordCount() method return -1 with MySQLi driver

### ISSUE THREAD

**Issue by noskill24** [ADOdb/ADOdb#394]
ADODB v5.20.9
PHP v7.1.10 - libmysql - mysqlnd 5.0.12-dev - 2015-04-07
MariaDB v10.0.32 Stable 2017-08-07

The method RecordCount() of driver mysqli always return -1 because the var $ADODB_COUNTRECS is not correctly set in the methods of mysqli driver.

See also:
https://sourceforge.net/p/adodb/bugs/31/

**Comment by dregad** [comment]
@noskill24, John Lim closed the SourceForge issue you referenced with status _closed-works-for-me_, meaning he was not able to reproduce the problem.

Can you please provide instructions to reproduce the problem ?

**Comment by noskill24** [comment]
I can't reproduce because this is not my server and configuration is unknown. But I can provide more info about this issue.

Setting $ADODB_COUNTRECS to TRUE before adoNewConnection("MySQLi") did fix problem for me.

Can you please tell me where you set $ADODB_COUNTRECS to FALSE for MySQLi-driver.
How you check the driver supports records counting in your source files?

**Comment by mnewnham** [comment]
The global [$ADODB_COUNTRECS](http://adodb.org/dokuwiki/doku.php?id=v5:reference:adodb_countrecs) is by default set to false in ADOdb. This is to eliminate needless calls to the database function mysql_num_rows (or the equivalent depending on the database in use) after every select. There was a time (Mysql versions < 5 ) when a call like that on a few million rows could take upwards of 10 seconds so the method needed to be called only when absolutely neccessary.

There are a couple of databases (access,sqlite) that don't have a native method for doing this so to do it we have to emulate the function by doing a SELECT COUNT(*), which is why we maintain the variable in the product.

Given that this function returns pretty much instantaneously now, given hardware and database performance, I recommend just adding the global 
````php
$ADODB_COUNTRECS=true;
````
to your startup files
