### ISSUE TITLE
Broken text database support

### ISSUE THREAD

**Issue by rexxitall** [ADOdb/ADOdb#397]
I would like to have the text database support back even in PHP7 :)
The reason is quite simple. If you need to have a simple text file aka as ini or setup file
you can easy maintain it with this simple solution and
maybee move it later if the app is "grewn up and looks like windows 96 ;) " migrate to a normal database.
Its also handy while developing for test cases.
So please be so kind and fix it :)
Now you have a serious user request for this feature :)
Thanks for you really nice work, its easy and simple  to use as well as the code is readable.
A very big thanks for that.
I tried this cumbersome PDwhatever .... Forget it !
I am not a esotheric guru neither a ZEN master - so really thanks again for let me get rid of that !
Best regards
Thomas

**Comment by dregad** [comment]
@rexxitall as [mentioned in the documentation](http://adodb.org/dokuwiki/doku.php?id=v5:database:text), the _Plain text_ driver is deprecated and does not work with PHP 5.3 and later due to the fact that it relies on a different signature for the `Execute()` function.

As things stand, I don't really see how this could be adapted for later versions of PHP, and to be honest I don't have the bandwitdh or even the interest to try and fix it. If you are able to provide a pull request for this, we would of course review and consider merging it.

If not or until then, I please consider using SQLite if you need a simple (but proper) database, or fallback to PHP native file functions to read your text file (e.g. [fgetcsv()](http://php.net/manual/en/function.fgetcsv.php).
