### ISSUE TITLE
start function names always with a lowercase char

### ISSUE THREAD

**Issue by peterdd** [ADOdb/ADOdb#421]
It is constantly annoying that many functions within ADOdb start with uppercase chars.

Because php function names are case-insensitive, changing it for the whole adodb project shouldn't have any bad sideeffects (except work updating adodb documentation wiki)

Benefits:

* better readability !!!
* consistency
* faster typing

**Comment by dregad** [comment]
I agree with this, and in fact if you look at [the documentation](http://adodb.org), all functions names are (or should be) starting with a lowercase letter. This has not (yet) been reflected in the codebase, but it should be done at some point.

**Comment by peterdd** [comment]
Ok, will start. How can I make fixes/pull requests for adodb.org dokuwiki?

**Comment by peterdd** [comment]
see #424 and #425

**Comment by dregad** [comment]
Thanks @peterdd. 

>see #424 and #425

If you don't mind, I'd prefer to have a single PR (with one commit per fixed file if you want), rather than PRs. It facilitates review and testing.

> How can I make fixes/pull requests for adodb.org dokuwiki?

You can't - this is a restricted access wiki. Please file issues here (or add notes to this thread), referencing the page that you'd like us to change, and describe the needed corrections; if you want you can copy/paste the revised, raw DokuWiki text.

**Comment by peterdd** [comment]
Ok, wanted to minimize potential merge conflicts with other open pull requests and thought just easier for review beginning with a view core files as they affect the wording uncertainty everywhere(code, doku, issues and pull request here, inherited class files last but not least projects using ADOdb)
Still ok to merge #424 and #425?

Ok, spotted some in the wiki, will report as issues here.

**Comment by dregad** [comment]
We have agreed to use camelCase for functions naming, and this gets gradually changed in the code base over time.

I'm going to close this issue, but please do submit more PR's to fix more if you'd like.
