### ISSUE TITLE
mssqlnative: output inserted not supported on INSERT statement for non-identity column

### ISSUE THREAD

**Issue by jlcfly** [ADOdb/ADOdb#470]
I have a table that users a uniqueidentifier for the id column instead of it being an identity column. The uniqueidentifier has a default value of newid() so it always gets a SQL-generated UUID. When inserting, in order to get the id, I use "output inserted.id" in my SQL statement. For example:

insert into mytable (value1, value2)
output inserted.id
values ('test1', 'test2'

SQL will put the id in to a field named id.

I've narrowed this down to a logic rule in adodb-mssqlnative.inc.php in the _query() function where it's detecting whether the $sql is an insert, and if so, it appends a semi-colon, then the $this->identitySQL; (which is defaulted to SCOPE_IDENTITY()). Because of this, the function never has a chance to retrieve the column because "select SCOPE_IDENTITY()" is executed and the results of the output inserted is never returned. In this case, there would never be a result because there is no true identity column.

Suggesting a change from this in _query():
```
if(preg_match('/^\W*insert[\s\w()",.\[\]]+values\s*\((?:[^;\']|\'\'|(?:(?:\'\')*\'[^\']+\'(?:\'\')*))*;?$/i', $sql)) {
    $insert = true;
    $sql .= '; '.$this->identitySQL; // select scope_identity()
}
```

To this:
```
if(preg_match('/^\W*insert[\s\w()",.\[\]]+values\s*\((?:[^;\']|\'\'|(?:(?:\'\')*\'[^\']+\'(?:\'\')*))*;?$/i', $sql)) {
    $insert = true;

    // Check if "output inserted'" is included. If so, do not attempt to append identitySQL
    if (!preg_match('^\W*insert[\s\w()",.\[\]]+output\s+inserted\.\w+\s+values\s*\((?:[^;\']|\'\'|(?:(?:\'\')*\'[^\']+\'(?:\'\')*))*;?$', $sql)) {
        $sql .= '; '.$this->identitySQL; // select scope_identity()
    }
}
```

**Comment by mnewnham** [comment]
I'm not sure that adding a second expensive regexp into the _query method for SQL server is an appropriate solution for this. The existing identitySQL workaround already adds a performance hit as it is executed for every statement and it would be nice to get rid of that. As there has never (to my knowledge) been a request to handle this kind of scenario, perhaps a local solution would be better.
**Suggestion 1**
Depending on your local configuration, because identitySQL is a public variable, you could simply blank it out before executing an insert on your  _mytable_

**Suggestion 2**

[Subclass the existing driver](http://adodb.org/dokuwiki/doku.php?id=v5:learn_extensions:extend_existing:modify_existing_driver). You might be able to make your code a lot more efficient here if it was tailored to your own sites requirements, so instead of your second complex regexp, you could do something like
````php
if(preg_match('/^\W*insert[\s\w()",.\[\]]+values\s*\((?:[^;\']|\'\'|(?:(?:\'\')*\'[^\']+\'(?:\'\')*))*;?$/i', $sql) 
&& stripos('output inserted') === false) 
    $insert = true;
````

**Comment by mnewnham** [comment]
As we have not heard from you for a while, I assume you have resolved this appropriately. Feel free to reopen if you need further help
