### ISSUE TITLE
getAssoc returns key column as value column with setFetchMode(ADODB_FETCH_BOTH)

### ISSUE THREAD

**Issue by dragonardx** [ADOdb/ADOdb#600]
In php 7.3 getAssoc() returns key column as value column.
Steps to reproduce error:
1. $ax = $DB->getAssoc("SELECT user,count(*) FROM logins GROUP BY user");
2. $ax result:
["john"]=> string(4) "john"
3. $ax expected result (like in php 5.3) should be:
["john"]=> string(2) "68"

problem in addodb v5.20.15.

when setFetchMode() is called with argument ADODB_FETCH_ASSOC
then getAssoc() works as expected.

**Comment by dregad** [comment]
Looks like the same issue as #204 and #459.

Problem confirmed in latest master (88106d48a4e6c0d212ba9f82f57a0ef91efb12dd),

**Comment by dragonardx** [comment]
I solved this issue by changing library function GetAssoc() in file adodb.inc.php in such way:
```
function GetAssoc($sql, $inputarr=false,$force_array = false, $first2cols = false) {
	    //fix start...
        $mode = $this->fetchMode;
        $moded = false;
        if ($mode != ADODB_FETCH_ASSOC) {
            $this->setFetchMode(ADODB_FETCH_ASSOC);
            $moded = true;
        }
        $rs = $this->Execute($sql, $inputarr);
        if ($moded) {
            $this->setFetchMode($mode);
        }
        //fix end...
        if (!$rs) {
			return false;
		}
		$arr = $rs->GetAssoc($force_array,$first2cols);
		return $arr;
	}
```

**Comment by mnewnham** [comment]
Your solution to the bug is problematical, (although fine for your own needs)  getAssoc is available as both `ADOConnection::getAssoc(`) and `ADORecordSet::getAssoc()`.  in fact the ADOConnection method is really just a wrapper for the ADORecordSet method. So if we change the Connection method to auto-switch from `ADODB_FETCH_BOTH`  to `ADODB_FETCH_ASSOC` automatically in the  connection method and not in the recordsetMethod, we would get different results from the 2 of them
````php
$ar = $db->getAssoc($sql);
$ar = $db->execute($sql)->getAssoc();
````
So that the 2 methods provide the same results, the control needs to be in the `ADORecordSet::getAssoc()` method. 

The version in master is a complete rewrite of the 5.20 version. The focus was in simplifying and removing numerous iterative loops across the recordset, but for the purposes of this discussion, it's a question of looking at the fetch method **when the query was executed**, available as ``$query->connection->fetchMode``, and then manipulating the recordset as necessary for the ADODB_FETCH_BOTH.

I've fixed the problem in master in the above patch. (@dregad , could you pull, annotate as necessary and kill the branch, thanks). Given the late stage of V5.20, and the incompatibility between the 2 releases. I don't really see a hotfix as necessary unless somebody else is interested in doing it.
