### ISSUE TITLE
Array to string conversion on exception with query parameters

### ISSUE THREAD

**Issue by hschletz** [ADOdb/ADOdb#601]
The ADODB_Exception constructor does not handle queries with parameter arrays. Patch attached.

[adodb-fix-exception-param.patch.txt](https://github.com/ADOdb/ADOdb/files/4076397/adodb-fix-exception-param.patch.txt)

**Comment by mnewnham** [comment]
Could you provide a simple code snippet to simplify the testing process please.

**Comment by hschletz** [comment]
I can't tell the exact circumstances that create the error condition. In my case, the problem occurs when a query raises an exception, but only when the code is called by PHPUnit. PHPUnit's own error handling may contribute to the problem. I could not reproduce the issue with a simple test script, other than invoking the ADODB_Exception constructor directly.

Here's the backtrace that leads to the warning (last call first, i.e. the warning is raised in adodb-exceptions.inc.php:45):
````
adodb-exceptions.inc.php:45
adodb-exceptions.inc.php:80
adodb.inc.php:306
adodb.inc.php:1277
adodb.inc.php:1237
adodb.inc.php:1808
adodb.inc.php:1641
````
The $fn parameter has the value "adodb_throw", leading to the code path in line 45. The problematic $p2 parameter contains the query parameters as an array, leading to the "array to string conversion" in that line.
The "CONNECT" and "PCONNECT" cases would be affected by the same issue. My patch converts the parameter manually, possibly breaking the "EXECUTE" case. Maybe $fn should be checked for "EXECUTE" before the conversion.

**Comment by hschletz** [comment]
[adodb-fix-exception-param-v2.patch.txt](https://github.com/ADOdb/ADOdb/files/4096758/adodb-fix-exception-param-v2.patch.txt)
Updated patch: don't mangle $p2 in case of EXECUTE.

**Comment by dregad** [comment]
@hschletz thanks for your contribution. It would be nice if you could submit patches via pull requests instead of attaching diff files, it would make it easier for us to review and merge.

**Comment by dregad** [comment]
@hschletz Thanks for the PR. Before merging it, I'd like to have a better understanding of the error's root cause. This is a bit difficult as you did not provide full stack trace details including function names and parameters. 

Nevertheless, the `adodb.inc.php:306` call (ADODB_TransMonitor function) seems to be the key*. 

Can you please confirm that you are using transactions (specifically, StartTrans and CompleteTrans) in your code ? I believe the explanation for the error could be that the `$fn` parameter in _ADODB_TransMonitor()_ (the value of which I assume is _EXECUTE_, based on the call at line 1277) is overwritten (line 305) by the original exception thrower (ie. `adodb_throw`).

If so, then maybe the correct fix for the problem is to rename the `$fn` variable in _ADODB_TransMonitor()_, like this:
```diff
diff --git a/adodb.inc.php b/adodb.inc.php
index 74c52e00..2a7c1ca9 100644
--- a/adodb.inc.php
+++ b/adodb.inc.php
@@ -302,8 +302,8 @@ if (!defined('_ADODB_LAYER')) {
        //print "Errorno ($fn errno=$errno m=$errmsg) ";
        $thisConnection->_transOK = false;
        if ($thisConnection->_oldRaiseFn) {
-           $fn = $thisConnection->_oldRaiseFn;
-           $fn($dbms, $fn, $errno, $errmsg, $p1, $p2,$thisConnection);
+           $errfn = $thisConnection->_oldRaiseFn;
+           $errfn($dbms, $fn, $errno, $errmsg, $p1, $p2,$thisConnection);
        }
    }
```

Can you please test and let me know ?

* Note: you did not specify which version you're using, so I'm assuming you're running 5.20.16 to interpret the line numbers.

**Comment by hschletz** [comment]
[test-issue-601.php.txt](https://github.com/ADOdb/ADOdb/files/4129065/test-issue-601.php.txt)
You are right, the problem occurs when exceptions get thrown within a transaction. So I was finally able to reproduce it with the attached test script.

Your patch works for me (applied against 5.20.16, as you guessed correctly).
