### ISSUE TITLE
MySQL Affected_Rows() returns number of rows selected instead of false for SELECT statements

### ISSUE THREAD

**Issue by mariobernheim** [ADOdb/ADOdb#604]
Hi, 
```
<?php
$sql = "SELECT * from subscribers WHERE number='".$number."' AND service_id='".$service_id."' LIMIT 1";
$rs  = $Conn->execute($sql);
if ($Conn->Affected_Rows()) {
    $active = $rs->fields['active'];    
    
    echo return_json_status("3","Number $number is subscribed to $service_id and is set active=$active");
    die("");
}
?>
```

For some reason this works... however, from the ADOdb Documentation, its not supposed to:

`https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:affected_rows`

Database: MySQL 5.7
Driver: Mysqli
PHP Version: PHP 7.0.33
ADOdb Version: V5.18

**Comment by mnewnham** [comment]
Database? Driver? PHP Version? ADOdb Version?

**Comment by mariobernheim** [comment]
Database: MySQL 5.7
Driver: Mysqli
PHP Version: PHP 7.2
ADOdb Version:  v5.20.14

**Comment by mariobernheim** [comment]
Database: MySQL 5.7
Driver: Mysqli
PHP Version: PHP 7.0.33
ADOdb Version: V5.18

**Comment by mariobernheim** [comment]
For references... I just tested this these

PHP Version: 7.2.25
ADOdb Version: v5.20.14

I do SELECT * from table limit 1 and Affected_Rows(); returns 1

**Comment by mnewnham** [comment]
This is due to a change in the behavior of the underlying mysqli_affected_rows(), which according to [The PHP documentation](https://www.php.net/manual/en/mysqli.affected-rows.php), now acts as mysqli_num_rows() for SELECT statements. In order to maintain cross-database compatibility, we need to suppress this behavior.

**Comment by mariobernheim** [comment]
Thanks, so for all purposes, we should be able to use Affected_Rows(); on all SELECT's as well and can consider it reliable?

**Comment by mnewnham** [comment]
No, you should not, because no other database supports it. The code will be changed so that it conforms to our standard, i.e. It will return false for SELECT statements

**Comment by mariobernheim** [comment]
Should we use RecordCount(); instead?

**Comment by mnewnham** [comment]
absolutely

**Comment by peterdd** [comment]
Maybe the example on https://adodb.org/dokuwiki/doku.php?id=v5:reference:connection:affected_rows should include an insert query too, ideally with 2 or 3 row values in the insert query to have a number >1 on success.

And maybe remove the select example there to avoid confusion or add an explanation. It is unclear from the example if table act contains just no rows or means 'error', so the 'Return false' there might be misinterpreted.

Otherwise this issue can be closed?

**Comment by mnewnham** [comment]
If you want to create a small example and paste it in here, I will happily update the documentation with it
