### ISSUE TITLE
Postgresql drivers show sql query all the time

### ISSUE THREAD

**Issue by gmaurice** [ADOdb/ADOdb#612]
Hello,
I'm installing testlink (https://github.com/TestLinkOpenSourceTRMS/testlink-code/tree/testlink_1_9)
and i was faced to a problem due to the following lines which are printed all the time.
I'm really disappointed because i don't know how to suppress this output.

There is no debug parameter to control these outputs : 
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-postgres64.inc.php#L569
https://github.com/ADOdb/ADOdb/blob/master/drivers/adodb-pdo_pgsql.inc.php#L180

It let me believe people don't use postgresql with php :D 
By the way, someone have any piece of advice ?

Thank you for your answer.

**Comment by dregad** [comment]
Well this code is 13 years old and I can only guess as to John Lim's reasons not to wrap the outp() call with an `if($this->debug) {`.

That being said, you getting there means that execution of the metaDefaultSQL statement (to retrieve the default values) failed, which is probably symptomatic of some other, underlying problem. 

Since I don't know or use testlink, and considering that you are not providing any actual output or details about your code or environment, I'm afraid there's not much more that I can do.

**Comment by mnewnham** [comment]
I agree with @dregad . The most likely reason for this message is passing an invalid table name into the metaColumns function. The issue with the debugging is a symptom of the problem, not the cause. For further assistance, please enable debugging and post some logs.

**Comment by mnewnham** [comment]
As we have not heard from you on this, we assume you have resolved it yourself. Feel free to re-open if you need further assistance
