### ISSUE TITLE
Warnings flagged with PHP 7.4.7 in adodb-odbc.inc.php 

### ISSUE THREAD

**Issue by simonwilsher** [ADOdb/ADOdb#618]
The following warnings are being flagged in adodb-odbc.inc.php (also used in adodb-ads.inc.php?) when using PHP 7.4.7:

PHP Warning: Use of undefined constant ODBC_BINMODE_RETURN - assumed 'ODBC_BINMODE_RETURN' (this will throw an Error in a future version of PHP)

PHP Warning: Use of undefined constant SQL_CUR_USE_DRIVER - assumed 'SQL_CUR_USE_DRIVER' (this will throw an Error in a future version of PHP)

**Comment by davidsneighbour** [comment]
I had that earlier with a MySQLi driver. I searched for the usage of these constants and defined them before including adodb. This might come up in more than those three drivers.

**Comment by mnewnham** [comment]
Could you provide platform, driver, database please

**Comment by simonwilsher** [comment]
In this instance, it was Windows Server 2016, PHP 7.4.7 (x64) and ODBC connecting to an SAP SQL Anywhere 17 DB.

**Comment by mnewnham** [comment]
This looks to be a problem with the ODBC driver/PHP module, I'm guessing the PHP ODBC module isn't being loaded correctly because both these constants exist in the [PHP ODBC module](http://gcov.php.net/PHP_HEAD/lcov_html/ext/odbc/php_odbc.c.gcov.php) for PHP 7.4, and that is where we are pulling them from. 

I can't find any evidence of PHP7 support for SQL Anywhere under windows. If you have a link to PHP7 dlls I could try and test this.

**Comment by simonwilsher** [comment]
Agreed. It appears to be a misconfiguration of the PHP and the ODBC PHP module, as it's only occurring on one of our servers, so not likely to be a adodb issue.

**Comment by mnewnham** [comment]
Aware you aware of any PHP Drivers for SQL Anywhere, or do you use a generic driver?

**Comment by simonwilsher** [comment]
Using vanilla ODBC in this instance.

There was a PHP module for SQL Anywhere (https://wiki.scn.sap.com/wiki/display/SQLANY/The+SAP+SQL+Anywhere+PHP+Module) but support went dormant after PHP 7.3
