### ISSUE TITLE
QMagic function was removed

### ISSUE THREAD

**Issue by oburk** [ADOdb/ADOdb#684]
Hi,

I have the following error message in my application after updating to release 5.21.0.

```php
Calling an undefined method ADODB_mysqli::QMagic()
```

Yes, it was no longer recommended to use the magic quote functions, so I replaced them with `qstr()`. 
But I didn't expect the `QMagic` function to be completely removed in a minor release (#657). Is this not a bug?

Best Regards

Oliver

**Comment by dregad** [comment]
Not a bug at all.

I'll grant you that the removal of *qMagic()* function (see #674) may have been a bit sudden, considering that we only [officially deprecated it in 5.20.20](https://github.com/ADOdb/ADOdb/blob/v5.20.20/adodb.inc.php#L875), and did not do that in a highly visible manner, either. 

That said, please consider that _magic quotes_ functions have been deprecated in PHP for many years (since 5.3, IIRC), and effectively do absolutely nothing [since PHP 5.4](https://www.php.net/ChangeLog-5.php#5.4.0); from the changelog:
> magic_quotes_gpc, magic_quotes_runtime and magic_quotes_sybase ini options. get_magic_quotes_gpc, get_magic_quotes_runtime are kept but always return false, set_magic_quotes_runtime raises an E_CORE_ERROR.

So it didn't make sense for us to keep qMagic() around, as it was de facto just an alias to qStr(), and required extra code to maintain PHP 8.0 compatibility.

**Comment by steffendietz** [comment]
I think nobody is debating the need to deprecate and ultimatively remove or change functionality.
However, since `composer` came around, we now have an established model how to handle such needs and prevent packages which depend on libraries such as `ADOdb` to accidentally receive an incompatible version.

With semantic versioning as soon as you change method signatures or remove public methods you bump the mayor version, and this ticket would have never been created.

I think this would be a good time to adopt a semantic versioning compatible release model.

**Comment by dregad** [comment]
> With semantic versioning as soon as you change method signatures or remove public methods you bump the mayor version, and this ticket would have never been created.

You're right, but what's done is done and we're not going to change the version number now. 

As mentioned, qStr() is a drop-in replacement for qMagic() since PHP 5.4. so fixing the problem should be as simple as `sed -ri "s/qMagic/qStr/gi"`.

Sorry about the inconvenience, and we'll pay closer attention to avoid such situation in the future.
