### ISSUE TITLE
mssqlnative: _insertid() doesn't work anymore

### ISSUE THREAD

**Issue by obmsch** [ADOdb/ADOdb#692]
In versions prior to 5.21 the `lastInsertID` was set/retrieved inside
`_query()` for insert statements and `_insertId()` just returned that value.
This worked because appending `; select SCOPE_IDENTITY()` to the original
sql makes it a batch, which surely has the same scope.

I guess using a new query in `_insertid()` to get that information doesn't
work (always `null`) because its a different scope from the insert query.

I run into this while testing MantisBT with ADOdb 5.21, every op which
inserts a record in table1 and needs the id of this record for an insert
in table2 fails.

I suggest to revert (works for me in the test), and look at other problems
with `_query()` (affected rows, triggers, unset `lastInsertID`) later.

I could offer a pull request, but not sure which branch to target.

**Comment by mnewnham** [comment]
We have had to make a change to the way it retrieved the insertid in the driver. In the  5.20 series, the code was calling the SQL server routines to retrieve the value of the last insertid for **every** insertion even if the request was inappropriate( no auto-increment column) or unneeded (not interested in the value). Although this was great for ease of use, this caused a measurable slowdown compared to 5.19, so we decided to revert to that versions way of doing it, which is that the _insertid actually makes the request to the database, rather than reading a stored value. This also gives us the ability to read the insert id from a stored procedure.

This does create the problem that in order to obtain the last insert id you need to call **insert_id()** early, as soon as the command has executed and before the query has closed out. This is in fact similar to other databases.  

If it's not possible for you to modify your code to get an early reading of the value, you will need to override both the **_insertid()** and the **_query()** methods to get the necessary code back in place.

**Comment by obmsch** [comment]
I see the rationale for the change, but I have no idea how that's supposed to work.

  >This does create the problem that in order to obtain the last insert id you need to call insert_id() early, as soon as the command has executed and before the query has closed out. This is in fact similar to other databases.
  
So to simulate the fastest possible way to obtain the last insert id, I modified _query():
```
	// returns query ID if successful, otherwise false
	function _query($sql,$inputarr=false)
	{
		$this->_errorMsg = false;

		if (is_array($sql))
			$sql = $sql[1];

		$insert = false;
		// handle native driver flaw for retrieving the last insert ID
		if(preg_match('/^\W*insert[\s\w()[\]",.]+values\s*\((?:[^;\']|\'\'|(?:(?:\'\')*\'[^\']+\'(?:\'\')*))*;?$/i', $sql)) {
			$insert = true;
			$sql .= '; '.$this->identitySQL; // select scope_identity()
		}
		if($inputarr)
		{
			/*
			* Ensure that the input array is numeric, as required by
			* sqlsrv_query. If param() was used to create portable binds
			* then the array might be associative
			*/
			$inputarr = array_values($inputarr);
			$rez = sqlsrv_query($this->_connectionID, $sql, $inputarr);
		} else {
			$rez = sqlsrv_query($this->_connectionID,$sql);
		}

		if ($this->debug) ADOConnection::outp("<hr>running query: ".var_export($sql,true)."<hr>input array: ".var_export($inputarr,true)."<hr>result: ".var_export($rez,true));

		if(!$rez) {
			$rez = false;
		} else if ($insert) {
			$rez2 = sqlsrv_query($this->_connectionID,$this->identitySQL);
			sqlsrv_fetch($rez2);
			$lastId = sqlsrv_get_field($rez2, 0);
			ADOConnection::outp("<hr>Last insert id: ".var_export($lastId,true));
		}

		return $rez;
	}
```
No luck with that (always `null`). From the docs:

  >Returns the last identity value inserted into an identity column in the same scope. A scope is a module: a stored procedure, trigger, function, or batch. Therefore, if two statements are in the same stored procedure, function, or batch, they are in the same scope.
  
I would argue, that appending `'; '.$this->identitySQL;` to the original sql makes it a batch, whereas executing two separate queries doesn't.

**Comment by mnewnham** [comment]
I agree that adding the $this->identitySQL makes it a batch. This is unfortunately the only way that we have been able to successfully retrieve the last insert id in a way that makes it cross-compatible with other drivers. This isn't really the problem though. The problem is the sequence of commands necessary to retrieve the value afterwards:

If we do execute them immediately afterwards as we do in 5.20,  it guarantees that the value of insertId is correct.  The problem is the amount of time that issuing
```php
sqlsrv_fetch($rez2);
$lastId = sqlsrv_get_field($rez2, 0);
````
takes when it is issued for every insert statement. So we've taken the decision to uncouple that command from the query.
The problem with this is that  as soon as we issue any other sql command against the database, the value of the  the lastId is lost. That is what I mean when I talk about calling insertId() early.

**Comment by dregad** [comment]
@mnewnham maybe I'm missing something here since I don't know or use mssql, but if I'm reading this right, the expected sequence is as follows, which is basically what we do in MantisBT.
```
$db->execute('INSERT ...');
$id = $db->insert_id();
```

1. the execute() call runs the batch statement `INSERT ...; select SCOPE_IDENTITY()` via ADODB_mssqlnative::_query()
2. ADOConnection::insert_id() calls ADODB_mssqlnative::_insertid(), which actually runs `sqlsrv_query($this->_connectionID,$this->identitySQL);` 

So the _identitySQL_ is called a second time, which I guess counts as _issue(ing) any other sql command against the database_ and therefore fails to return the ID ?

**Comment by obmsch** [comment]
@dregad yes having that `$insert` checks in place is a leftover and unnecessary. But
removing them wouldn't change anything. The problem is, that you can't get the 
`SCOPE_IDENTITY()` from a second query. It has to be (appended) in the `INSERT` to be a batch.
So we are trading performance (inserts in tables with no IDENTITY col, caller doesn't mind)
over functionality here. Nothing wrong with that. Just not good for MantisBT.

What about making this configurable, so a client has the choice. Actually we have `var $hasInsertID = true;`,
which is simply not true anymore. So lets change that to `false`. I wouldn't mind to utilize anything else
(`var $withSCOPE_IDENTITY = false;`). 

```
	class ADODB_mssqlnative extends ADOConnection {
		...
		var $hasInsertID = false;
```

and

```
	function _insertid()
	{
		// SCOPE_IDENTITY(), set in _query() if appropriate
		// Returns the last IDENTITY value inserted into an IDENTITY column in
		// the same scope. A scope is a module -- a stored procedure, trigger,
		// function, or batch. Thus, two statements are in the same scope if
		// they are in the same stored procedure, function, or batch.
		return $this->lastInsertID;
	}
```

and

```
	function _query($sql,$inputarr=false)
	{
		$this->_errorMsg = false;

		if (is_array($sql)) $sql = $sql[1];

		$insert = false;
		
		if ($hasInsertID) {
			// handle native driver flaw for retrieving the last insert ID
			if(preg_match('/^\W*insert[\s\w()[\]",.]+values\s*\((?:[^;\']|\'\'|(?:(?:\'\')*\'[^\']+\'(?:\'\')*))*;?$/i', $sql)) {
				$insert = true;
				$sql .= '; '.$this->identitySQL; // select scope_identity()
			}
		}
		
		if($inputarr) {
			$rez = sqlsrv_query($this->_connectionID, $sql, $inputarr);
		} else {
			$rez = sqlsrv_query($this->_connectionID,$sql);
		}

		if ($this->debug) ADOConnection::outp("<hr>running query: ".var_export($sql,true)."<hr>input array: ".var_export($inputarr,true)."<hr>result: ".var_export($rez,true));

		if(!$rez) {
			$rez = false;
		} else if ($hasInsertID && $insert) {
			// retrieve the last insert ID (where applicable)
			while ( sqlsrv_next_result($rez) ) {
				sqlsrv_fetch($rez);
				$this->lastInsertID = sqlsrv_get_field($rez, 0);
			}
		} else {
			$this->lastInsertID = null;
		}
		return $rez;
	}

```

So the only thing a client (MantisBT) has to do to get back to old behaviour, is set that var to true. That's a
simple change (@dregad feasible?).

**Comment by dregad** [comment]
So I finally bit the bullet, and setup my Ubuntu dev box with an SQL Server docker, and the mssqlnative driver for PHP to test this. As a side note, this went surprisingly smoothly... I remember running into so many problems trying to do that a few years back that I gave up on it.

Anyway, I tried to reproduce the problem in a simple test script, and was quite surprised to notice that `insert_id()` **did** return the last insert id, but the MantisBT code did not, even though they both basically did `$db->execute(...); $db->insert_id();` with no database-related code executed between them. (I even tried to add `var_dump($g_db->insert_id());` immediately after the [$g_db->Execute call in DbQuery class](https://github.com/mantisbt/mantisbt/blob/release-2.25.0/core/classes/DbQuery.class.php#L292), but still that returned _null_. 

So contrary to what @mnewnham said, it would seem to be impossible to retrieve the id without running a custom version of ADOdb, which I don't want to do.

Then I looked closer, at the queries, and noticed that **you can retrieve the ID when executing a query without parameters**, but insert_id() returns NULL if there are any params, i.e.
``` php
<?php
include 'adodb.inc.php';

$db = ADONewConnection('mssqlnative');
$db->connect('localhost', $u, $p, $d);

echo "Last ID = " . $db->getOne('SELECT id FROM test ORDER BY id DESC') . "\n";

echo "Inserting with param... ";
$rs = $db->execute("INSERT INTO test VALUES (?)", date('c'));
echo "ID: "; var_dump($db->insert_id());

echo "Inserting a simple query... ";
$rs = $db->execute("INSERT INTO test VALUES ('" . date('c'). "')");
echo "ID: "; var_dump($db->insert_id());
```
Results
```
Last ID = 14
Inserting with param... ID: NULL
Inserting a simple query... ID: string(2) "16"
```

WTF !? :angry: 
Maybe you guys have an idea why we get different results with parameterized queries ?

@mnewnham what do you think of making this behavior configurable as suggested by @obmsch ?

**Comment by peterdd** [comment]
`$rs = $db->execute("INSERT INTO test VALUES (?)", date('c'));`

Just by reading thus I think you must pass an array of parameters instead a string.

**Comment by mnewnham** [comment]
@peterdd is correct, you must pass an array of parameter to SQL Server execute. So the correct syntax must be:
````php
$rs = $db->execute("INSERT INTO test VALUES (?)", array(date('c'));. 
````
If you do that you should be able to retrieve the insert id. Incidentally I've been running master in my own production systems for years with no issues on the SQL Server driver. 

Regarding parameterization, I've no objection at all, I love parameterization. I could parameterize things all day.  i would ask though that the existing 5.21 remains the no-config default. Also that the consequences of changing the defaults is documented, particularly the performance hit, I know Mantis isn't a batch product and it's not relevant for that but that was the whole reason for reversion

**Comment by dregad** [comment]
> Just by reading: I think you must pass an array of parameters instead of string.

Makes no difference
``` php
$rs = $db->execute("INSERT INTO test VALUES (?)", [date('c')]);
```
Still NULL.

**Comment by mnewnham** [comment]
OK let me look at some of my production code. Seriously, I've pulled millions of Insert ids from both prepared and ordainary statements.

**Comment by dregad** [comment]
> Maybe you guys have an idea why we get different results with parameterized queries ?

Possible explanation, according to [this MSDN forum thread](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/2100b805-50d7-409c-882d-bac1d441e6e0/scopeidentity-returns-null-after-paramerized-insert?forum=transactsql):

_What happens is that when you use parameterised SQL, the API will wrap the INSERT statement in a call to sp_executesql. You can see this if you use Profiler to spy on what is actually being sent to SQL Server._

**Comment by dregad** [comment]
So that leaves us with the configuration option 

> i would ask though that the existing 5.21 remains the no-config default

That's fine with me, and it can even remain the default going forward as far as I'm concerned, since in most cases it is not necessary to retrieve the Insert Id. It would be good enough to be able to specifically activate this whenever the client needs it.

And I agree that we need to properly document this, and its consequences.

**Comment by dregad** [comment]
> > i would ask though that the existing 5.21 remains the no-config default
> 
> That's fine with me, and it can even remain the default going forward as far as I'm concerned, since in most cases it is not necessary to retrieve the Insert Id. It would be good enough to be able to specifically activate this whenever the client needs it.

I have been thinking about this, and I changed my mind. Consider the pros and cons of enabling the extra SCOPE_IDENTITY query by default, which I outlined in the table below:

Last Insert Id|pro|con
---|---|---
Enabled | Id can be retrieved for all insert queries | Unnecessary performance hit when Insert Id is not actually needed
Disabled | Faster performance for the general use case | Broken functionality for parameterized queries <br> regression from 5.20

I therefore strongly believe we should give precedence to functionality over performance improvement here, especially considering that 
- we broke a behavior that had been working in a production release since 2014 (feature was introduced in 5.19, see #5, and later improved in 5.20.0, see #41).; 
- the performance hit really applies to batch scenarios inserting a large number of records only;
- there is a very simple way to disable the functionality for cases where performance does matter

**Comment by peterdd** [comment]
I'm not using mssql, so maybe a dumb question, but why can't the insertid of an INSERT be retrieved directly by using the result of an execute()?

This way no extra $db->insert_id() is required, right?

I also use Perl's DBI and their execute() https://metacpan.org/pod/DBI#execute says:

`For a non-SELECT statement, execute returns the number of rows affected, if known. If no rows were affected, then execute returns "0E0", which Perl will treat as 0 but will regard as true. Note that it is not an error for no rows to be affected by a statement. If the number of rows affected is not known, then execute returns -1.`

**Comment by dregad** [comment]
> why can't the insertid of an INSERT be retrieved directly by using the result of an execute()?

@peterdd Not sure what you mean by _retrieved directly_ - in ADOdb, execute() returns ADORecordSet object so there is no more direct way of getting the Id than calling insert_id() for that recordset. 

I don't understand why you are referencing Perl DBI returning a record count, which is a completely different topic - more relevant would be [last_insert_id](https://metacpan.org/pod/DBI#last_insert_id), noting that they are facing the same issue being discussed here, i.e. _For some drivers the value may only be available if placeholders have not been used (e.g., Sybase, MS SQL)_, which we address by executing the extra `select SCOPE_IDENTITY()` statement after the initial SQL.

**Comment by peterdd** [comment]
@dregad forget my stupid comment, it was a long night of coding and tired and my brain mixed affected rows with insert id. 😳😱🙈
