### ISSUE TITLE
Inefficiency in adodb-mssqlnative.inc.php

### ISSUE THREAD

**Issue by LouisJohnson** [ADOdb/ADOdb#70]
I've noticed that the _FetchField() function in ADORecordset_mssqlnative repeatedly calls sqlsrv_field_metadata, and this function is called in a loop in _initrs()

storing the result of sqlsrv_field_metadata in a class property and reusing allowed great performance gains for me, especially when using result sets with many fields.

my snippet on line 938: 
if(!isset($this->metaCache)) {
            $fa = @sqlsrv_field_metadata($this->_queryID);
            $this->metaCache = $fa;
        } else $fa = $this->metaCache;

**Comment by dregad** [comment]
It seems a bit strange to initialize the property within _FetchField()... Instinctively I would do this in _initrs(), especially considering that sqlsrv_field_metadata() is already called there once, and then just reuse the property in _FetchField(). Thoughts?

**Comment by mnewnham** [comment]
I think I already have the appropriate code for this, which I have been using for a number of years and which is not database specific. It modifies adodb-lib.inc,php and caches metadata, columns and recordsets and allows reuse. I did offer this to John many years ago but he raised some objection which I cannot remember now. Performance improvements are substantial when inserting or updating multiple records on the same table. I will tag this as an enhancement request and we can review this as an addition to a later release

**Comment by mnewnham** [comment]
Having just re-reviewed the driver, in fact as @dregad suggested it should be in _initrs(). In that method there is the following:

```php
$fieldmeta = sqlsrv_field_metadata($this->_queryID);
$this->_numOfFields = ($fieldmeta)? count($fieldmeta):-1;
/*
* Copy the oracle method and cache the metadata at init time
 */
if ($this->_numOfFields>0) {
    $this->_fieldobjs = array();
    $max = $this->_numOfFields;
    for ($i=0;$i<$max; $i++) $this->_fieldobjs[] = $this->_FetchField($i);
}
```

So the code is actually there in _initrs(). in fetchField we just need to look up fieldObjs.  it just looks like the code was not completed. I will look at this soon.

**Comment by mnewnham** [comment]
This issue has been fixed here: https://github.com/ADOdb/ADOdb/commit/a4cfda2daa197d249ccada31aecb9d37fd16ddb7

Details as follows:

Updating of the mssqlnative driver to reduce schema reads. This is done by reading and caching the schema for the requested table at the initial table request, resulting in a single call to sqlsrv_field_metadata().  All subsequent requests use the cached schema information.  This method is copied from the method used in the oci8 driver. In addition, the following changes have been made:

1. Date fields are handled better, the ReturnDatesAsStrings parameter is now passed in the connection, and the system can now distinguish between date(91) and datetime(93) fields correctly, and format them according to standards. This is done using the 'format' callback for the date/time field.

2. The field object is now returned as an ADOFieldObject instead of an array, making it compatible with other drivers.

3. Driver now supports sequence creation in SQL Server 2014

This fix should be considered beta quality, as there have been substantial changes to the mssqlnative driver. No other changes to ADOdb have been made, @LouisJohnson , maybe you could consider testing,

**Comment by dregad** [comment]
Mark, if you don't mind, I suggest you amend the commit message so that the 1st line briefly describes what the patch does, e.g. *improve mssqlnative driver efficiency* or something similar, and move the `Fixes #70` bit down to the commit message body. This makes future maintenance easier.

Thanks for the patch

**Comment by dregad** [comment]
@mnewnham I have amended the commit as per our discussion. Note that I force-pushed the branch, so make sure you update your local repo accordingly.

**Comment by dregad** [comment]
@mnewnham this was targeted at 5.20 release, can you please confirm whether it can go in as-is (i.e. can I merge the *mssqlnative-fixes* branch), or if further work/review is necessary on your end ?

**Comment by mnewnham** [comment]
As we are going straight to production with 5.20, I would prefer to see it in 5.21.0-alpha,  but that is ultimately your call.

**Comment by dregad** [comment]
Considering that 5.20dev has been out there for so long, it can effectively be considered to be alpha-tested ;)

**Comment by dregad** [comment]
That being said, you authored the code and I can't test MSSQL so it more your call than mine, really. I'll change the milestone to 5.21

**Comment by dregad** [comment]
@mnewnham OK to merge this branch into master (5.21) now ?
