### ISSUE TITLE
Mysql autoExecute() update doesnt work anymore in v5.21.0

### ISSUE THREAD

**Issue by leon-mbs** [ADOdb/ADOdb#721]
When update sql  is  generated  it  puts  brackets  instead  native  quotes

see     
 vendor\adodb\adodb-php\adodb-lib.inc.php       line  681

```
if ((strpos($upperfname,' ') !== false) || ($ADODB_QUOTE_FIELDNAMES)) {
	switch ($ADODB_QUOTE_FIELDNAMES) {
		case 'BRACKETS':
			$fnameq = $zthis->leftBracket.$upperfname.$zthis->rightBracket;break;
		case 'LOWER':
			$fnameq = $zthis->nameQuote.strtolower($field->name).$zthis->nameQuote;break;
		case 'NATIVE':
			$fnameq = $zthis->nameQuote.$field->name.$zthis->nameQuote;break;
		case 'UPPER':
```

The  ADODB_QUOTE_FIELDNAMES variable  is  **true**   so BRACKETS is  selected

Anyway  it  was  wrong  before    but BRACKETS case wasn't there,  so always  LOWER was  selected  so  it  worked

Thanks

**Comment by dregad** [comment]
Regression introduced by #246. Consequently, the same problem also exists with _adodb_getinsertsql().

With regards to fixing the bug, the most obvious thing to do would be to revert to the pre-5.21.0 behavior, i.e. `true`== `LOWER`. 

That being said, the [documentation for  $ADODB_QUOTE_FIELDNAMES](https://adodb.org/dokuwiki/doku.php?id=v5:reference:adodb_quote_fieldnames) states that for `true` there is _no case handling of the field name_. As I  understand this, `true` is actually expected to behave like `NATIVE`. We also need to consider that the code has been handling `true` as `LOWER` since 2011/v5.13 (see 3a831fcec0cd59ec26d68798d2f27a33c1ead131) until 5.21.0, and before that it meant `UPPER`...

@mnewnham what do you think ?
- revert to true == LOWER (5.20 status) and fix documentation
- consider true == LOWER to be a bug introduced in 5.13, and revert to true == UPPER + fix documentation
- fix the code so true == NATIVE so it matches (my understanding of) the documentation

**Comment by mnewnham** [comment]
Ya know, I hate feature creep like this where we've got bools and strings doing the same thing, however....

Given that true meant UPPER prior to 2011, I think we should discard that as an option. I also suspect that that is where the documentation came from.  I would propose

````php
ADODB_QUOTE_NONE = 0; //resolves to false
ADODB_QUOTE_LOWER = 1; //resolves to true,   match to "LOWER", deprecate "LOWER"  in future release
ADODB_QUOTE_UPPER = 2; //match to "UPPER", deprecate "UPPER" in future release
ADODB_QUOTE_NATIVE = 3; // match to "NATIVE", deprecate "NATIVE"  in future release
ADODB_QUOTE_BRACKETS = 4; // match to "BRACKETS", deprecate "BRACKETS" in future release
````

We're also talking about quoting changes elsewhere in #685

How does that sound?

**Comment by dregad** [comment]
Replacing the strings with constants was going to be my next suggestion, so we're aligned. I'm fine with your proposal, will submit a PR as time allows.

**Comment by dregad** [comment]
I'm having second thoughts about this.

Originally, $ADODB_QUOTE_FIELDNAMES controlled two things: quoting (on/off) and case conversion (upper, lower, native). This is questionable but still OK as there was only one quote style. The _BRACKETS_ option changed this, as it introduced a second quoting style, which can now be _off_, _on_ (= use regular quotes) or _brackets_.

So the question is, do we actually need to be able to control case when quoting with brackets ? If so, we need to either
- control case with a separate setting (maybe use ADODB_ASSOC_CASE ?)
- define additional constants so we can control case as well as quote tyle (ADODB_QUOTE_BRACKETS_LOWER, ADODB_QUOTE_BRACKETS_UPPER, ADODB_QUOTE_BRACKETS_NATIVE)

A third option could be to get rid of the leftBracket/rightBracket properties introduced in #246, store them in the existing nameQuote property as an array (override the default setting in the drivers as appropriate), and provide an ADOConnection method to let user switch quote style. $ADODB_QUOTE_FIELDNAMES goes back to its original role of controlling the case. This is more generic and flexible, but also more complex to implement.

What do you think ?

**Comment by dregad** [comment]
One more thing, as I just realized that the current behavior is not consistent... 

The table below shows the actual values returned by the fieldnames quoting logic, given input `Field` (and `Field Name` for the _false_ case), with a _mysqli_ connection :

$ADODB_QUOTE_FIELDNAMES | 5.20.20 | 5.21.0 | Expected ?
--- | --- | --- | ---
false | ``` FIELD ``` <br> ``` `FIELD NAME` ``` :question:(1) | ``` FIELD ``` <br>``` `FIELD NAME` ``` :question:(1) | ``` field ``` <br> ``` `field name` ``` (4)
true | ``` `field` ``` :question:(2) | `[FIELD]` :x:(3) | ``` `field` ``` 
LOWER | ``` `field` ``` :heavy_check_mark:  | ``` `field` ``` :heavy_check_mark:  | ``` `field` ```
UPPER | ``` `FIELD` ``` :heavy_check_mark:  | ``` `FIELD` ``` :heavy_check_mark:  | ``` `FIELD` ```
NATIVE | ``` `Field` ``` :heavy_check_mark:  | ``` `Field` ``` :heavy_check_mark:  | ``` `Field` ```
BRACKETS | N/A - Defaults to _UPPER_ :heavy_check_mark: | `[FIELD]` :heavy_check_mark: | `[FIELD]` (4)

Note: the :question: in the _true_ and _false_ cases, denotes unexpected behavior
1) Handling of _false_ is consistent with [documentation](https://adodb.org/dokuwiki/doku.php?id=v5:reference:adodb_quote_fieldnames) which states that _The default behavior of autoExecute is to quote field names, and **convert them to upper case**_, but
2) In that case, _true_ should probably convert to uppercase also, although it no longer does since 5.13 [as mentioned above](https://github.com/ADOdb/ADOdb/issues/721#issuecomment-815921198)
3) This is the bug reported by @leon-mbs  that started this whole discussion
4) If we switch to lowercase as the default, shouldn't this be lowercase too ?

**Comment by mnewnham** [comment]
Hells bells I didn't think it would be this complicated, and in some way I think I've suppressed  the fact for ever that the casing in this was not controlled by ADODB_ASSOC_CASE. But now I think I understand this and why ADODB_ASSOC_CASE isn't used 

Think of 2 different operations: 
1. **_Reading_** the database and presenting the associative data keys in a consistent manner and casing in order to make use of array functions etc. So **ADODB_ASSOC_CASE** is actually **ADODB_ASSOC_READ_CASE**.
2. Presenting the database with data to be **_written_**. I like to use DB2 for this as an example because it has true case sensitivity, and quotes can affect how the data is written to the database. 
      - "EMPLOYEE","employee" and "Employee" can be 3 separate columns in the same table.   
      - If I have a statement that says "SELECT Employee FROM STAFF", but the column name is actually EMPLOYEE, then the statement will still succeed (as long as there is not a column called Employee in the same table)
      - But if I quote the field name and say "SELECT 'Employee' FROM STAFF, then the statement will fail because I am forcing the parser to not auto-resolve the columns.
 3. Therefore we must break down the writing into 2 separate things, the casing and the quoting, so instead of the table above (which is very nice I must say, I'd like to see the source of that if possible) what we actually need is a matrix, with casing options on the X axis, and quoting options on the Y axis

````
ADODB_WRITE_OPTIONS = ADODB_WRITE_CASE + ADODB_WRITE_QUOTING
````

Note also another difference between reading and writing is that there is no numeric option to writing, so maybe we need to reinforce this difference in the documentation.

### My New Suggestions
####5.21.1
Just hotfix this back to the original setting of 5.20.19. That buys us some time to get this in order for 5.22
####5.22
1. Lets break casing and quoting apart completely. 
2. I would if possible like to see us moving away from constants and globals and replacing them with class variables. It would be nice to start compartmentalizing these things so that we could for example, quote fields on one connection and not another. I had to connect an Oracle database to a MySQL one once, and the constants were a real nuisance.

#### Casing
Thats easy, just follow the ADODB_ASSOC_CASE values
#### Quoting
Maybe something like this
QUOTE_NONE   = 0
QUOTE_SINGLE = 1
QUOTE_DOUBLE = 2
QUOTE_BRACKETS = 3
QUOTE_CUSTOM = 4
Option 4 would need some mechanism to build and use them.

I think we should also bring in the QUOTE_ALL and standardize that.

**Comment by dregad** [comment]
> Hells bells I didn't think it would be this complicated

Tell me about it... what a can of worms :astonished:  

> So **ADODB_ASSOC_CASE** is actually **ADODB_ASSOC_READ_CASE**.

Right, I get it.

> "EMPLOYEE","employee" and "Employee" can be 3 separate columns in the same table.

That would be a silly thing to do IMHO, but I see the point.

> 3. Therefore we must break down the writing into 2 separate things, the casing and the quoting
> what we actually need is a matrix, with casing options on the X axis, and quoting options on the Y axis

That was my gut feeling too, so we're aligned.

> there is no numeric option to writing, so maybe we need to reinforce this difference in the documentation.

Not sure what you mean, can you please clarify ?

> #### 5.21.1
> Just hotfix this back to the original setting of 5.20.19. That buys us some time to get this in order for 5.22

That fixes the regression introduced by the `BRACKETS` option, but leaves us with the inconsistent case conversion when using true / false... 

It would be an easy fix to uniformize casing. Are you saying we should postpone addressing this to 5.22 ? 

> #### 5.22
> 1. Lets break casing and quoting apart completely.
> 2. I would if possible like to see us moving away from constants and globals and replacing them with class variables.

Agreed.

> #### Casing
> Thats easy, just follow the ADODB_ASSOC_CASE values

OK

> #### Quoting
> 
> Maybe something like this
> QUOTE_NONE = 0
> QUOTE_SINGLE = 1
> QUOTE_DOUBLE = 2
> QUOTE_BRACKETS = 3
> QUOTE_CUSTOM = 4
> Option 4 would need some mechanism to build and use them.

I'm not sure this setting needs to be so detailed, or even that it makes sense to let the user select quote style like this, since it is driven by the database driver (e.g. mysql accepts ``` ` ``` but not `"` unless [ANSI_QUOTES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes) is enabled).

I believe the following should be sufficient, along with the existing `$nameQuote` property and  a setQuoteStyle() method accepting one of the constants.

QUOTE_NONE = 0
QUOTE_SINGLE = 1 // $nameQuote . $field . $nameQuote
QUOTE_BRACKETS = 2 // $nameQuote[0] . $field . $nameQuote[1]

> I think we should also bring in the QUOTE_ALL and standardize that.

What do you mean ?

----
And finally, per your request
> the table above (which is very nice I must say, I'd like to see the source of that if possible)

That is made with standard [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), you should be able to see the source if you click the 3 dots menu in the top-right of the post then select _reference in new issue_; if that does not work for you I can copy/paste the raw markdown and e-mail it to you. Let me know.

**Comment by mnewnham** [comment]
> 
> > there is no numeric option to writing, so maybe we need to reinforce this difference in the documentation.
> 
> Not sure what you mean, can you please clarify ?
Just meant that from a documentation point, we should ensure that ADODB_ASSOC_CASE isn't relevant in write operations 

> 
> > #### 5.21.1
> > Just hotfix this back to the original setting of 5.20.19. That buys us some time to get this in order for 5.22
> 
> That fixes the regression introduced by the `BRACKETS` option, but leaves us with the inconsistent case conversion when using true / false...
> 
> It would be an easy fix to uniformize casing. Are you saying we should postpone addressing this to 5.22 ?

Don't understand how you would achieve that in the current code without removing the brackets option.

> 
> > #### 5.22
> > 
> > 1. Lets break casing and quoting apart completely.
> > 2. I would if possible like to see us moving away from constants and globals and replacing them with class variables.
> 
> Agreed.
> 
> > #### Casing
> > Thats easy, just follow the ADODB_ASSOC_CASE values
> 
> OK
> 
> > #### Quoting
> > Maybe something like this
> > QUOTE_NONE = 0
> > QUOTE_SINGLE = 1
> > QUOTE_DOUBLE = 2
> > QUOTE_BRACKETS = 3
> > QUOTE_CUSTOM = 4
> > Option 4 would need some mechanism to build and use them.
> 
> I'm not sure this setting needs to be so detailed, or even that it makes sense to let the user select quote style like this, since it is driven by the database driver (e.g. mysql accepts `` ` `` but not `"` unless [ANSI_QUOTES](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes) is enabled).
> 
> I believe the following should be sufficient, along with the existing `$nameQuote` property and a setQuoteStyle() method accepting one of the constants.
> 
> QUOTE_NONE = 0
> QUOTE_SINGLE = 1 // $nameQuote . $field . $nameQuote
> QUOTE_BRACKETS = 2 // $nameQuote[0] . $field . $nameQuote[1]
> 
Could we not simplify it down then to either 
````
QUOTE_NONE = 0;
QUOTE_ALL = 1;
````
where $nameQuote always becomes an array and the default becomes for example with MySQL ("`","`") [backtick,backtick] 

> > I think we should also bring in the QUOTE_ALL and standardize that.
> 
> What do you mean ?
> 
I was thinking of #685 and namequote()

> And finally, per your request
> 
> > the table above (which is very nice I must say, I'd like to see the source of that if possible)
> 
> That is made with standard [GitHub Flavored Markdown](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown), you should be able to see the source if you click the 3 dots menu in the top-right of the post then select _reference in new issue_; if that does not work for you I can copy/paste the raw markdown and e-mail it to you. Let me know.

Got it, thanks

**Comment by dregad** [comment]
> > It would be an easy fix to uniformize casing. Are you saying we should postpone addressing this to 5.22 ?
> 
> Don't understand how you would achieve that in the current code without removing the brackets option.

BRACKETS is already consistent in terms of case, because the field is always uppercased so there is no need to change that.


> Could we not simplify it down then to either
> 
> ```
> QUOTE_NONE = 0;
> QUOTE_ALL = 1;
> ```
> 
> where $nameQuote always becomes an array and the default becomes for example with MySQL ("`","`") [backtick,backtick]

Considering $nameQuote is a public property, for BC I think we should keep supporting $nameQuote as string.

Moreover, supporting both single and bracket quote styles (for DBs allowing that) would require a separate, extra operation to set the quoting tokens (e.g. `$db->nameQuote = ['[', ']'];` or `$db->setQuoteStyle('[', ']');`) which is a low-level thing that IMO should be abstracted away.

My proposed approach simplifies that by hiding the low-level logic within the driver-specific method, e.g. 
```php
// MySQL
function setQuoteStyle(int $style) {
  $this->nameQuote = $style ? '`' : '';
}

// MSSQL
function setQuoteStyle(int $style) {
  switch ($style) {
      case QUOTE_NONE: 
        $this->nameQuote = ''; // or ['"', '"']
        break;
      case QUOTE_BRACKETS: 
        $this->nameQuote = ['[', ']']; 
        break;
      case QUOTE_SINGLE: 
      default:
        $this->nameQuote = '"';  // or  ['', '']
        break;
}
```

**Comment by mnewnham** [comment]
OK I think I understand that
