### ISSUE TITLE
Prepared statements still emulated in MySQL

### ISSUE THREAD

**Issue by mwbelt** [ADOdb/ADOdb#762]
I downloaded the latest stable, after using a deprecated version for awhile.  Am I correct in reading that prepared statements are still not *actually* prepared in MySQL?  For the sake of security, should I just give in and use native prepared statements instead?

drivers/adodb-mysql.inc.php says:

        function Prepare($sql)
        {
                /*
                * Flag the insert_id method to use the correct retrieval method
                */
                $this->usePreparedStatement = true;

                /*
                * Prepared statements are not yet handled correctly
                */
                return $sql;
                $stmt = $this->_connectionID->prepare($sql);
                if (!$stmt) {
                        echo $this->errorMsg();
                        return $sql;
                }
                return array($sql,$stmt);
        }

**Comment by mwbelt** [comment]
@dregad Any word on when 5.22.0 will be released?  I know it was targeted for October, but I don't see any recent mention of it.  I'm going to production with a new project soon and would love to have an official release.

Thanks!

**Comment by dregad** [comment]
Yeah, the deadlines have slid somewhat, sorry... I'm working on the release actually so hopefully it will be out in the next few days.

**Comment by mwbelt** [comment]
@dregad any word this?

**Comment by mwbelt** [comment]
@dregad anything?

**Comment by dregad** [comment]
The 2.22.0 release was cut one month ago https://github.com/ADOdb/ADOdb/releases/tag/v5.22.0
Did I miss something ?

**Comment by mwbelt** [comment]
@dregad when I didn't see a reply to my question from January, I stopped checking back regularly, and didn't refresh the tab to the main repo, so it still showed 5.21.x.  Glad 5.22 is released, thank you.

**Comment by ervishal** [comment]
but looks like issue is still there of not supporing prepared statement? 
            /*
            * Prepared statements are not yet handled correctly
            */
            return $sql;
its just return the plain sql in mid of the function.
please let me know if I am missing anything?

**Comment by ervishal** [comment]
I am having this mysql version 
mysql> SELECT VERSION();
+--------------------------------------------+
| VERSION()                                  |
+--------------------------------------------+
| 10.3.12-MariaDB-1:10.3.12+maria~xenial-log |
+--------------------------------------------+
1 row in set (0.00 sec)
I am getting this error
mysql> execute cmd using @param1;
ERROR 1615 (HY000): Prepared statement needs to be re-prepared

after search found this link which exactly happening in case
https://stackoverflow.com/questions/29480915/mysql-view-prepared-statement-and-prepared-statement-needs-to-be-re-prepar

other then SET table_definition_cache value to be higher side is there any other solution for this? anything to do with Mariadb/mysql version?

**Comment by mnewnham** [comment]
1. Prepared statements are indeed handled natively and have been for quite a while.  
2. Could you confirm that you are using the natiive MySQL driver, and not PDO
3. My quick research on this suggests that the following MySQL parameter changes may fix the problem

 `SET GLOBAL table_definition_cache = 1024 `

(https://mariadb.com/kb/en/library/server-system-variables/#table_definition_cache)

**Comment by ervishal** [comment]
@mnewnham thanks for responding!
1. ok that was I also think of but wanted to confirm. but question is then why adodb-mysqli.inc.php have `return $sql;` here https://github.com/ADOdb/ADOdb/blob/v5.22.7/drivers/adodb-mysqli.inc.php#L1093 in `function Prepare($sql)` ? before executing entire function body?
in our case since long we execute a patch file which simply remove this `return $sql;` from `Prepare function` body. 
Another thing since long time `adodb-php:5.20.21` version days but had no issues until recently when we upgraded to 5.22.7; `this prepare statement needs to be reprepared` surfaced. any insight here will help me explain to LT.
2. yes we are using natiive MySQL driver if you are talking about `mysqli`; this is how we use `$DB_TYPE = 'mysqli';` please confirm if you asked something else.
3. yes that I figured out this is the solution along with that discovered that our mariadb version is 10.3.12 but going to be upgrade to 10.6.15 soon. Dbas assuming this would resolve the issue. however I am still concern why it did not appear earlier. 
my instinct is there was major overwhelming changes happened to the way prepared statment used to execute inside adodb-php:execute. please let me know if you have insight.

**Comment by dregad** [comment]
@ervishal in the future kindly open a separate Issue, instead of exhuming a 3 years-old, closed one. You can always reference an issue with `#<id>`. Thanks
