### ISSUE TITLE
adodb-db2-inc.php - FetchField returns inconsistent value type for char field

### ISSUE THREAD

**Issue by maxicampa** [ADOdb/ADOdb#78]
FetchField for db2 returns STRING instead of CHAR against char fields.
Actually the function db2_field_type returns STRING instead of CHAR and FetchField passes up this value.
In my opinion, in order to be consistent with the other drivers (ODBC, SQLite, MySql, etc) , FetchField should returns CHAR.
Not sure if should be done inside FetchField or inside db2_field_type.

**Comment by dregad** [comment]
I don't use db2 and don't have access to it. Feel free to provide a pull request to fix this issue.

**Comment by mnewnham** [comment]
Remember, `db2_field_type()` is the PHP function itself. `FetchField()` is simply returning the result of this function.

Where there are possible compatibility issues  like this, the normal course would be to create an adodb-db2po (portable) driver. However, I contributed substantial amounts to the DB2 driver some time ago and do not remember this being an issue. It may be I have not used Fetchfield in the same way as you. 

Perhaps we could open this up for a discussion as to the need for a portable driver. Perhaps maxicampa would be prepared to contribute some code.

**Comment by mnewnham** [comment]
It's taken me a little while to dig into this and provide an explanation. I'm going to close this as well, but if you need further help, feel free to re-open,

The fetchfield function returns the raw type as provided by the database driver, so as you have pointed out, for a char field db2 returns 'string'. Many databases do return 'char', but many others do not. For example, the mysqli driver returns the number 253 for a char field, sql server returns 1 for a char and 12 for a varchar.

In order to obtain the cross-database compatibility, it is always necessary to feed the result of fetchfield into the `metaType()`  method. The result, for all the above examples is `C`. It is this result you need to work with.

~~~~~
$fld = $recordSet->FetchField($offset);
$type = $recordSet->MetaType($fld->type);
~~~~~~~



Mark
