### ISSUE TITLE
oci8: support setting the client identifier

### ISSUE THREAD

**Issue by eminemma** [ADOdb/ADOdb#805]
Hi, the *oci_set_client_identifier()* method allows you to set the client identifier used by various database components to identify lightweight application users authenticating as the same database user (traceability end to end and audit).

**Comment by dregad** [comment]
To my knowledge, the notion of client identifier is quite specific to Oracle, I don't think there is an equivalent in other DBs.

@eminemma since you seem to be interested in having more functionality implemented in the oci8 driver, maybe you would be willing to contribute this feature with a pull request ?
