### ISSUE TITLE
ValueError: str_repeat(): Argument #2 ($times) must be greater than or equal to 0

### ISSUE THREAD

**Issue by Mike-Benoit** [ADOdb/ADOdb#852]
ValueError: str_repeat(): Argument #2 ($times) must be greater than or equal to 0 on adodb/adodb-lib.inc.php:1255

A recent change (b83d290e1ca42f51c92900f295a251ab53b3e253) to that line uses str_repeat(), but $tabs can be lower than 0 in some cases.
```
$s .= str_repeat($html ? ' &nbsp; ' : "\t", $tabs);
```

Not sure why exactly $tabs is going into the negatives, but a quick ternary on it gets rid of the warning at least:
```
$s .= str_repeat($html ? ' &nbsp; ' : "\t", $tabs >= 0 ? $tabs : 0 );
```

**Comment by dregad** [comment]
I didn't consider such scenario. Of course applying a minimum value of 0 will fix this, but I'd like to understand the root cause.

The variable is set a few lines above 
```php
	array_shift($traceArr);
	array_shift($traceArr);
	$tabs = sizeof($traceArr)-2;
```
We're removing 2 entries from the backtrace with the array_shift() calls, so the `sizeof($traceArr)-2` seems unnecessary.

Do you have some real-life example where this is causing a problem ?
