### ISSUE TITLE
oci8: unused $seqField property

### ISSUE THREAD

**Issue by dregad** [ADOdb/ADOdb#933]
I noticed this while working through #926, which was proposing to [define the missing property](diff-3a56b24a3d2ff2ad0e0f6730891b93687b5d57fccd4679a9bf5df81113848603) to fix the PHP 8.2 deprecation notice:

https://github.com/ADOdb/ADOdb/blob/bb87e83338c99038986878ac78f680becf9e8091/drivers/adodb-oci8.inc.php#L322-L327

The *seqField* property is used in the data dictionary, but not referenced anywhere else in the driver.

This was introduced by you in #565,  so maybe you'll remember what you were trying to achieve... If not I'd suggest to remove the if statement, as it feels like a mistake.

**Comment by mnewnham** [comment]
So here is what I was trying to achieve, I think. With oracle, there wasn't really the option to create autoincrement columns the way most other databases do, so what we have instead is the create record trigger that uses a sequence to do an on-insert update of an integer column that puts an incrementing value into the column.

The change I made then was because Johns original code started failing when Oracle allowed column names longer than (I think) 16 columns. I also tried to make the code portable so that if _insertId() was called and there wasn't an auto-increment column in the table, the function just returned immediately instead of doing the whole code flow including the getOne() at the end. 

My mistake here was to confuse the code being executed for the dictionary for the stuff in the main system. I would like to have something there but thats clearly not the right approach.

**Comment by dregad** [comment]
Thanks for your reply. This what I thought but it's good to have confirmation. 

To get rid of the PHP 8.2 deprecated warning, I propose to just remove the if statement for now since it's not doing anything useful. 

If you want I can open a separate issue to track the need for detection of the auto-numbering sequence, and we can work on finding a proper fix for that later.

**Comment by dregad** [comment]
> If you want I can open a separate issue to track the need for detection of the auto-numbering sequence

Done, see #936

**Comment by mnewnham** [comment]
Ok thanks for looking at that. I started it but found that I couldn't get an oracle connection up and running at home. I will try to do something as soon as I can but I recognize that it's not ultra-important.
