### ISSUE TITLE
Full table scan when accessing sessions table on MySQL

### ISSUE THREAD

**Issue by mariobernheim** [ADOdb/ADOdb#941]
### Description
When investigating why a table with more than 300k sessions was degrading performance in general, I decided to run the queries directly and noticed that the culprit was in this query:

`UPDATE sessions2 SET expiry = NOW() + INTERVAL 23328000 SECOND ,expireref='', modified = NOW() WHERE /*! BINARY */ sesskey = 'cbadsafveiim47emnj0mhi17qk' AND expiry >= NOW()`

since its doing a full table scan, in higher traffic websites, this will hinder the mysql performance considerably.

### Environment
- ADOdb version: v5.20.17
- Driver or Module: mysqli
- Database type and version: mysql 5.7
- PHP version: php 7.2
- Platform: almalinux

* [x] I have tested that the problem is reproducible in the [latest release](https://github.com/ADOdb/ADOdb/releases/latest) / **master** branch / **hotfix** branch

### Steps to reproduce
create 300k sessions with adodb db session handler - with each session update; it does a full table scan to update the expiry on the expiration column. 

### Expected behavior
Mysql performance degradation as more sessions are added into that table. 

###Additional context

**Comment by dregad** [comment]
Could you confirm that your `sessions2` table matches the [definition in the documentation](https://adodb.org/dokuwiki/doku.php?id=v5:session:session_index#mysql_or_pdo_mysql)

If I [create the table as described in the documentation](https://adodb.org/dokuwiki/doku.php?id=v5:session:session_index#mysql_or_pdo_mysql), and populate it with a large number of rows, I'm getting a full *index* (not table) scan
```
+----+-------------+-----------+------------+-------+---------------+---------+---------+------+--------+----------+-------------+
| id | select_type | table     | partitions | type  | possible_keys | key     | key_len | ref  | rows   | filtered | Extra       |
+----+-------------+-----------+------------+-------+---------------+---------+---------+------+--------+----------+-------------+
|  1 | UPDATE      | sessions2 | NULL       | index | sess2_expiry  | PRIMARY | 258     | NULL | 288429 |   100.00 | Using where |
+----+-------------+-----------+------------+-------+---------------+---------+---------+------+--------+----------+-------------+
```

I do get a full *table* scan, if I drop all indexes
```
+----+-------------+-----------+------------+------+---------------+------+---------+------+--------+----------+-------------+
| id | select_type | table     | partitions | type | possible_keys | key  | key_len | ref  | rows   | filtered | Extra       |
+----+-------------+-----------+------------+------+---------------+------+---------+------+--------+----------+-------------+
|  1 | UPDATE      | sessions2 | NULL       | ALL  | NULL          | NULL | NULL    | NULL | 282982 |   100.00 | Using where |
+----+-------------+-----------+------------+------+---------------+------+---------+------+--------+----------+-------------+
```

On my dev box, with 280k test rows, actually executing the update statement takes 0.43 sec with indexes, and 0.47 without, so only marginally worse, and a half second for a simple update is definitely too much.

So I'm thinking the problem may be caused by the `BINARY` cast; if I remove it:
```
mysql> explain UPDATE sessions2 SET expiry = NOW() + INTERVAL 23328000 SECOND ,expireref='', modified = NOW() WHERE sesskey = 'cbadsafveiim47emnj0mhi17qk' AND expir
y >= NOW();
+----+-------------+-----------+------------+-------+----------------------+---------+---------+-------+------+----------+-------------+
| id | select_type | table     | partitions | type  | possible_keys        | key     | key_len | ref   | rows | filtered | Extra       |
+----+-------------+-----------+------------+-------+----------------------+---------+---------+-------+------+----------+-------------+
|  1 | UPDATE      | sessions2 | NULL       | range | PRIMARY,sess2_expiry | PRIMARY | 258     | const |    1 |   100.00 | Using where |
+----+-------------+-----------+------------+-------+----------------------+---------+---------+-------+------+----------+-------------+
1 row in set, 1 warning (0.02 sec)
```

Considering that the *BINARY* operator is deprecated in MySQL 8.0 [[1]], I'm thinking we might remove it... we're comparing character data, so I'm not sure it's actually necessary anyway.

Could you please test on your end ?


[1]: https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#operator_binary

**Comment by mariobernheim** [comment]
Thank you - this query:

`UPDATE sessions2 SET expiry = NOW() + INTERVAL 23328000 SECOND ,expireref='', modified = NOW() WHERE sesskey = 'cbadsafveiim47emnj0mhi17qk' AND expiry >= NOW()`

`1 row affected. (Query took 0.0004 seconds.)`

Took less than 0.001 without this bit: 

/*! BINARY */

and not 0.09 seconds we're seeing under normal load and 0.40seconds we're seeing under lots of load.

**Comment by dregad** [comment]
> I'll remove the BINARY cast then.

I'm having second thoughts about this. 

Technically, a PHP session id can have characters matching `[A-Za-z0-9-,]`, so we could in theory have multiple ids differing only by case, which would be a problem with a non-binary (case insensitive) comparison, e.g. `SELECT * FROM sessions2 WHERE sesskey = 'ab2'` would match session 'Ab2'.

Of course there can be only one `ab2` session stored in the table (regardless of case) due to the primary key constraint on *sesskey* column, but this could nevertheless cause the handler to return data from someone else's session.

So if we were to remove the BINARY cast, we would need the *sesskey* column to have a binary collation (e.g. `utf8_bin`). This would break backwards compatibility, requiring all ADOdb Sessions users to update their *sessions2* table's structure.

Alternatively, if we apply the cast to the expression's right side, I believe the index would apply. 

@mariobernheim could you please test with
```sql
UPDATE sessions2 SET expiry = NOW() + INTERVAL 23328000 SECOND ,expireref='', modified = NOW() WHERE sesskey = /*! BINARY */ 'cbadsafveiim47emnj0mhi17qk' AND expiry >= NOW()
```
And also, for MySQL 8.0.27+ compatibility
```sql
UPDATE sessions2 SET expiry = NOW() + INTERVAL 23328000 SECOND ,expireref='', modified = NOW() WHERE sesskey = CAST('cbadsafveiim47emnj0mhi17qk' AS BINARY) AND expiry >= NOW()
```

**Comment by mariobernheim** [comment]
Thanks - I just tested this:

`UPDATE sessions2 SET expiry = NOW() + INTERVAL 23328000 SECOND ,expireref='', modified = NOW() WHERE sesskey = /*! BINARY */ 'cbadsafveiim47emnj0mhi17qk' AND expiry >= NOW()`

and its just as fast as if it didn't have /*!binary*/  - it scored 0.0002 second query time.

**Comment by mariobernheim** [comment]
is cast() 5.7 compatible? if not I'll go ahead and install 8.0 and test - however - do you recommend we manually change the position in the query?

**Comment by dregad** [comment]
> is cast() 5.7 compatible?

According to [the docs](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html) it is. 

> do you recommend we manually change the position in the query?

Not sure what you mean. The cast should be on the expression's right hand side, sesskey = cast('xxx' as binary)

**Comment by mariobernheim** [comment]
I'm just wondering if I should update to the latest version of adodb or to change this here  in these files - the whole stack where we found this is running on php 7.2 

`session/adodb-session.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-session.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-session.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-session.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-sess.txt:* sesskey is compared in BINARY mode for MySQL, to avoid problems with
session/adodb-sess.txt:  Of course, the user should define the sesskey field as BINARY, to
session/adodb-session2.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-session2.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-session2.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-session2.php:		$binary = $conn->dataProvider === 'mysql' ? '/*! BINARY */' : '';
session/adodb-sessions.mysql.sql:	sesskey		CHAR(32)	/*! BINARY */ NOT NULL DEFAULT '',
`

**Comment by dregad** [comment]
You're asking a piece of software's maintainer whether you should stay on an unsupported version or update ? Of course I'd recommend you upgrade to the latest version 😉 

You're welcome to try and patch your 5.20 of course... You could probably even apply the upcoming patch to 5.22 cleanly, as the Sessions module has not changed that much.

**Comment by mariobernheim** [comment]
Well - there's the issue that the newer versions of adodb need to be atleast php 7.4 - this stack is running 7.2 - of course for any new deployment we'd use 8.0 but this is 4 year old software - which is why i'm wondering if we can patch this in the meantime :)

**Comment by dregad** [comment]
ADOdb 5.22 runs on PHP 7.0. Only the upcoming 5.23 requires 7.4.

**Comment by mnewnham** [comment]
I've used adodb_sessions with the _**BINARY**_ removed for mysql for about 15 years now with no problem. I admit it isn't with PDO though. I'm also using it with PHP 8.0 no problem.

**Comment by mariobernheim** [comment]
> ADOdb 5.22 runs on PHP 7.0. Only the upcoming 5.23 requires 7.4.

Thank you - I'll wait until 5.22 gets patched up to replace our 5.20 - this will greatly improve performance!

**Comment by dregad** [comment]
> I've used adodb_sessions with the _**BINARY**_ removed for mysql for about 15 years now with no problem. I admit it isn't with PDO though. I'm also using it with PHP 8.0 no problem.

You would only potentially encounter problems when both conditions below are true:
- [session.sid_bits_per_character](https://www.php.net/manual/en/session.configuration.php#ini.session.sid-bits-per-character) == 6 (defaults to 4, recommended value is 5). With 5 or less, session ID will never contain any uppercase letters, so there's no risk of collision.
- The ADOdb sessions table's *sesskey* column has a case-insensitive collation

So to ensure the code works reliably in all environments, we need to either force case-sensitive comparison in the various SQL queries used in Sessions module functions, define *sessions2.sessid* as case-sensitive (e.g. use `utf8_bin` collation), or both.

**Comment by dregad** [comment]
> define sessions2.sessid as case-sensitive (e.g. use utf8_bin collation), 

Updated table creation SQL in the documentation to reflect this, and added explanation:
https://adodb.org/dokuwiki/doku.php?id=v5:session:session_index#mysql_or_pdo_mysql

**Comment by peterdd** [comment]
Wouldn't be charset ascii enough to store session key instead of an utf8*** charset ?

**Comment by dregad** [comment]
> Wouldn't be charset ascii enough to store session key instead of an utf8*** charset ?

Yes it would, but using ASCII character set would not solve the case sensitivity issue because the default collation is `ascii_general_ci `, so we'd have the to change that to `ascii_bin` and the fix would be exactly the same.

In any case, this is 2023 and I don't think it's good idea to store non-Unicode character strings in a database. MySQL's utf8mb4 uses variable-length (1-4 bytes) chars anyway so we would not be gaining anything by using ASCII.
