### ISSUE TITLE
SQLite3 Driver Double Inserting

### ISSUE THREAD

**Issue by ctassell** [ADOdb/ADOdb#99]
I for the life of me can't figure out why this is happening, but when you run an insert command with the SQLite3 driver it inserts two records instead of one.  I've tried the same query using the builtin PHP SQLite object and it seems to work fine.  Here is some example code with the schema:

CREATE TABLE sensor_log (
	sensor_log_id	INTEGER PRIMARY KEY,
	sensor_id	INTEGER,
	received_on	INTEGER,
	has_uploaded	BOOLEAN,
	temp_value	TEXT,
	level_value	TEXT
);

<?php

include("adodb.inc.php");

$query = "INSERT INTO sensor_log (sensor_id, temp_value) VALUES (2, 'test')";
$pathToDB = "sensorDB";

//$db = new SQLite3("$pathToDB");
//$db->exec($query);

$con = NewADOConnection("sqlite3");
$con->Connect("localhost", "me", "you", "$pathToDB");
$result = $con->Execute($query);

?>

**Comment by dregad** [comment]
I can reproduce this. 

Looks like the problem is caused by the sqlite3 driver relying on *SQLite3::query* to execute the statement, which returns an empty SQLite3Result while the _Execute methods expects *true* for handling of result-less queries. This causes the query to be executed a second time when ADOdb initializes the recordset for what it assumes is a SELECT statement.

I'll push a fix shortly.

**Comment by ctassell** [comment]
Yup, that seems to have fixed it.  Thank you very much!
